import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  en: {
    "app.name": "SENDA",
    "app.tagline": "Communication Hub",
    "tutorial.title": "Welcome to SENDA",
    "tutorial.description": "Watch this quick tutorial to get started with our system.",
    "nav.dashboard": "Dashboard",
    "nav.sms": "SMS",
    "nav.send_sms": "Send SMS",
    "nav.purchase_sms": "Purchase SMS",
    "nav.sender_names": "Sender Names",
    "nav.purchase_history": "Purchase History",
    "nav.contacts": "Contacts",
    "nav.campaigns": "Campaigns",
    "nav.partner_insights": "Partner Insights",
    "nav.integration_guide": "Integration Guide",
    "nav.partner_reference": "Partner Reference",
    "nav.settings": "Settings",
    "nav.messaging": "Messaging",
    "nav.ai_copilots": "AI Copilots",
    "nav.voice_copilots": "Voice Copilots",
    "nav.voice_ivr": "Voice / IVR",
    "nav.ivr_flows": "IVR Flows",
    "nav.phone_numbers": "Phone Numbers",
    "nav.calls": "Calls",
    "nav.recordings": "Recordings",
    "nav.audio_prompts": "Audio Prompts",
    "nav.voice_agents": "Agents",
    "nav.ai_call_intelligence": "AI & Call Intelligence",
    "voice.overview.subtitle": "Everything for building and running phone call experiences.",
    "voice.overview.ivr_flows_desc": "Build and publish call flows — menus, transfers, business hours, voicemail.",
    "voice.overview.phone_numbers_desc": "Connect each number to exactly one published flow.",
    "voice.overview.calls_desc": "See incoming and outgoing calls, their outcomes, and the flow steps taken.",
    "voice.overview.recordings_desc": "Every recorded call and voicemail, in one browsable list.",
    "voice.overview.ai_settings_desc": "Turn on post-call summaries, sentiment, and call intent detection.",
    "common.try_again": "Try again",
    "voice.calls.tab_all": "All",
    "voice.calls.tab_inbound": "Inbound",
    "voice.calls.tab_outbound": "Outbound",
    "voice.calls.tab_missed": "Missed",
    "voice.calls.range_7": "7d",
    "voice.calls.range_30": "30d",
    "voice.calls.range_90": "90d",
    "voice.calls.range_all": "All",
    "voice.calls.range_group_label": "Time range",
    "voice.calls.loading": "Loading…",
    "voice.calls.count_subtitle": "{{count}} calls, recorded and searchable",
    "voice.calls.search_placeholder": "Search callers, topics, transcripts…",
    "voice.calls.search_aria": "Search calls",
    "voice.calls.agent_aria": "Agent",
    "voice.calls.all_agents": "All agents",
    "voice.calls.sentiment_aria": "Sentiment",
    "voice.calls.any_sentiment": "Any sentiment",
    "voice.calls.sentiment_positive": "Positive",
    "voice.calls.sentiment_neutral": "Neutral",
    "voice.calls.sentiment_negative": "Negative",
    "voice.calls.no_match_title": "No calls match",
    "voice.calls.no_calls_title": "No calls yet",
    "voice.calls.no_match_desc": "Try another filter or a wider time range.",
    "voice.calls.no_calls_desc": "Real inbound or outbound calls will show up here.",
    "voice.calls.col_caller": "Caller",
    "voice.calls.col_agent": "Agent",
    "voice.calls.col_time": "Time",
    "voice.calls.col_length": "Length",
    "voice.calls.col_ai_summary": "AI Summary",
    "voice.calls.col_sentiment": "Sentiment",
    "voice.calls.no_recording": "No recording",
    "voice.calls.outbound_call": "Outbound call",
    "voice.calls.inbound_call": "Inbound call",
    "voice.calls.details": "Details",
    "voice.calls.from": "From",
    "voice.calls.to": "To",
    "voice.calls.outcome": "Outcome",
    "voice.calls.recording": "Recording",
    "voice.calls.stored": "stored",
    "voice.calls.no_recording_for_call": "No recording for this call.",
    "voice.calls.other_recordings": "Other recordings on this call",
    "voice.calls.transcript": "Transcript",
    "voice.calls.journey": "Journey",
    "voice.calls.load_more": "Load more",
    "voice.calls.error_loading": "Failed to load call history",
    "voice.calls.outcome_completed": "Completed",
    "voice.calls.outcome_failed": "Failed",
    "voice.calls.outcome_busy": "Line was busy",
    "voice.calls.outcome_no_answer": "No answer",
    "voice.calls.outcome_aborted": "Aborted",
    "voice.calls.outcome_rejected": "Rejected",
    "voice.calls.outcome_cancelled": "Cancelled",
    "voice.calls.outcome_technical_failure": "Network error",
    "voice.calls.outcome_ringing": "Ringing…",
    "voice.calls.outcome_in_progress": "In progress…",
    "voice.recordings.count_subtitle": "{{count}} recordings in storage",
    "voice.recordings.search_placeholder": "Search callers, numbers, agents…",
    "voice.recordings.search_aria": "Search recordings",
    "voice.recordings.error_loading": "Failed to load recordings",
    "voice.recordings.no_match_title": "Nothing matches",
    "voice.recordings.no_recordings_title": "No recordings yet",
    "voice.recordings.no_match_desc": "Try a different number or agent.",
    "voice.recordings.no_recordings_desc": "Recordings show up here once a call is recorded or a caller leaves a voicemail.",
    "voice.recordings.col_number": "Number",
    "voice.recordings.col_size": "Size",
    "voice.recordings.col_stored": "Stored",
    "voice.recordings.col_actions": "Actions",
    "common.try_again_desc": "Please try again.",
    "voice.ai_settings.error_loading": "Failed to load AI settings",
    "voice.ai_settings.save_failed": "Failed to update",
    "voice.ai_settings.enabled_toast_title": "AI Call Analysis turned on",
    "voice.ai_settings.enabled_toast_desc": "AI analysis is now on for your calls.",
    "voice.ai_settings.language_auto": "Detect automatically",
    "voice.ai_settings.language_sw": "Swahili",
    "voice.ai_settings.language_en": "English",
    "voice.ai_settings.toggle_summary": "Post-call summary",
    "voice.ai_settings.toggle_sentiment": "Customer sentiment",
    "voice.ai_settings.toggle_intent": "Reason for calling",
    "voice.ai_settings.toggle_categorization": "Topics and categorization",
    "voice.ai_settings.subtitle": "AI analysis of your call recordings — optional, off by default, and independent of the IVR engine.",
    "voice.ai_settings.enabled_desc": "AI can analyze call conversations to help you understand customer needs and improve service.",
    "voice.ai_settings.disabled_desc": "AI analysis is off. No AI analysis will be run on your calls.",
    "voice.ai_settings.consent_text": "SENDA will use conversation content to analyze calls and provide summaries along with important service information for customers.",
    "voice.ai_settings.toggles_title": "Choose what gets analyzed",
    "voice.ai_settings.toggles_desc": "Each analysis type can be switched off on its own, without disabling AI analysis entirely.",
    "voice.ai_settings.transcription_language_label": "Transcription language",
    "voice.ai_settings.realtime_label": "Real-Time Analysis",
    "voice.ai_settings.realtime_tooltip": "Requires a telephony line that streams audio live during the call — not available yet.",
    "voice.ai_settings.realtime_unavailable": "Not available",
    "voice.numbers.error_loading": "Failed to load phone numbers",
    "voice.numbers.created_toast_title": "Number added",
    "voice.numbers.created_toast_desc": "You can now connect it to an IVR flow.",
    "voice.numbers.create_failed": "Failed to add number",
    "voice.numbers.flow_connected_title": "Flow connected",
    "voice.numbers.flow_connected_desc": "This number now runs the selected flow.",
    "voice.numbers.update_failed": "Failed to update",
    "voice.numbers.number_saved": "Phone number saved",
    "voice.numbers.save_number_failed": "Failed to save number",
    "voice.numbers.recording_on_title": "Recording every conversation",
    "voice.numbers.recording_off_title": "Recording turned off",
    "voice.numbers.recording_on_desc": "Every call forwarded to an agent on this number will now be recorded.",
    "voice.numbers.recording_off_desc": "Forwarded calls will only be recorded when a flow explicitly asks for it.",
    "voice.numbers.disconnect_confirm": "Disconnect \"{{flow}}\" from {{number}}? Calls to this number will not be answered until you connect another flow.",
    "voice.numbers.this_number": "this number",
    "voice.numbers.copied_title": "Copied",
    "voice.numbers.copied_desc": "Webhook URL copied to clipboard.",
    "voice.numbers.subtitle": "Connect each number to exactly one published flow — that flow is what runs when the number is called.",
    "voice.numbers.add_number": "Add number",
    "voice.numbers.add_number_title": "Add a new number",
    "voice.numbers.add_number_desc": "Enter your number — no provider or flow is required to start; you can connect them later.",
    "voice.numbers.phone_label": "Phone number",
    "voice.numbers.display_name_label": "Display name (optional)",
    "voice.numbers.display_name_placeholder": "e.g. Customer Service",
    "voice.numbers.cancel": "Cancel",
    "voice.numbers.creating": "Adding…",
    "voice.numbers.save_number": "Save number",
    "voice.numbers.empty_title": "No phone numbers yet",
    "voice.numbers.empty_desc": "Add your phone number to start assigning it an IVR flow.",
    "voice.numbers.provider_none": "No provider",
    "voice.numbers.status_active": "Active",
    "voice.numbers.status_inactive": "Inactive",
    "voice.numbers.no_provider_notice": "Number added but not yet connected to a provider — contact SENDA so calls can start coming through.",
    "voice.numbers.active_flow_label": "Active flow",
    "voice.numbers.flow_connected_suffix": "is connected — this is what runs on every call to {{number}}.",
    "voice.numbers.disconnect": "Disconnect",
    "voice.numbers.no_flow_connected": "No flow connected",
    "voice.numbers.connect_flow_placeholder": "Connect a flow…",
    "voice.numbers.no_flows_prefix": "No published flows yet —",
    "voice.numbers.no_flows_link": "publish one first",
    "voice.numbers.webhook_label": "Webhook URL (paste into your provider's callback URL field)",
    "voice.numbers.record_title": "Record every conversation",
    "voice.numbers.record_desc": "Automatically records every call forwarded to an agent on this number.",
    "voice.numbers.edit_flow_prefix": "Edit",
    "voice.access.title": "Voice / IVR Access Required",
    "voice.access.desc": "You don't have access to Voice / IVR yet. Ask a workspace admin or SENDA support to enable it for your account.",
    "voice.plan.no_feature": "Your plan does not include the Voice/IVR feature.",
    "voice.ivr.error_loading": "Failed to load flows",
    "voice.ivr.error_loading_flow": "Failed to load flow",
    "action.buy_sms_credits": "Buy SMS Credits",
    "profile.profile": "Profile",
    "profile.settings": "Settings",
    "profile.logout": "Log out",
    "status.online": "Online",
    "theme.toggle": "Toggle theme",
    "user.loading": "Loading...",
    "user.user": "User",
    "user.no_email": "No email",
    "settings.language": "Language",
    "dashboard.welcome": "Welcome back 👋",
    "dashboard.subtitle": "Monitor your communication platform performance in real-time.",
    "dashboard.metric.total_messages": "Total Messages",
    "dashboard.metric.last_30_days": "Last 30 days",
    "dashboard.metric.active_contacts": "Active Contacts",
    "dashboard.metric.engaged_this_month": "Engaged this month",
    "dashboard.metric.campaign_success": "Campaign Success",
    "dashboard.metric.delivery_rate": "Delivery rate",
    "dashboard.metric.sender_id": "Sender ID",
    "dashboard.metric.approved_sender_names": "Approved sender names",
    "dashboard.metric.current_credits": "Current Credits",
    "dashboard.metric.available_credits": "Available credits",
    "dashboard.error.title": "Dashboard Error",
    "dashboard.error.description": "There was an error loading the dashboard.",
    "dashboard.error.hint": "Check the console for more details.",
    "dashboard.activity.title": "Recent Activity",
    "dashboard.activity.live": "Live",
    "dashboard.activity.none": "No recent activity",
    "dashboard.activity.view_all": "View all activity",
    "dashboard.quick_actions.title": "Quick Actions",
    "dashboard.quick_actions.send_message": "Send Message",
    "dashboard.quick_actions.send_message_desc": "Quick WhatsApp or SMS",
    "dashboard.quick_actions.add_campaign": "Add New Campaign",
    "dashboard.quick_actions.add_campaign_desc": "Bulk messaging campaign",
    "dashboard.quick_actions.add_contacts": "Add Contacts",
    "dashboard.quick_actions.add_contacts_desc": "Import or add manually",
    "dashboard.quick_actions.add_sender_id": "Add Sender ID",
    "dashboard.quick_actions.add_sender_id_desc": "Request new sender ID",
    "dashboard.quick_actions.need_help": "Need help?",
    "dashboard.quick_actions.contact_support": "Contact Support →",
    "dashboard.quick_actions.view_tutorial": "View Tutorial",
    "dashboard.quick_actions.tutorial_description": "Watch our video tutorial to learn how to use SENDA",
    "dashboard.recent_campaigns.title": "Recent Campaigns",
    "dashboard.recent_campaigns.view_all": "View all →",
    "dashboard.recent_campaigns.empty_title": "No campaigns yet",
    "dashboard.recent_campaigns.empty_subtitle": "Create your first campaign to get started",
    "dashboard.recent_campaigns.status.completed": "Completed",
    "dashboard.recent_campaigns.status.sending": "Sending",
    "dashboard.recent_campaigns.status.scheduled": "Scheduled",
    "dashboard.recent_campaigns.status.failed": "Failed",
    "dashboard.recent_campaigns.menu.view_details": "View details",
    "dashboard.recent_campaigns.menu.duplicate": "Duplicate",
    "dashboard.recent_campaigns.menu.edit": "Edit",
    "dashboard.recent_campaigns.progress": "Progress",
    "dashboard.recent_campaigns.sent": "Sent",
    "dashboard.recent_campaigns.delivered": "Delivered",
    "dashboard.recent_campaigns.opened": "Opened",
    "dashboard.sender_ids.title": "Active Sender IDs",
    "dashboard.sender_ids.active": "Active",
    "dashboard.sender_ids.table.sender_id": "Sender ID",
    "dashboard.sender_ids.table.status": "Status",
    "dashboard.sender_ids.table.sample_content": "Sample Content",
    "dashboard.sender_ids.table.created": "Created",
    "dashboard.sender_ids.empty_title": "No sender IDs found",
    "dashboard.sender_ids.empty_subtitle": "Sender IDs will appear here once they are approved",
    "dashboard.sender_ids.manage": "Manage sender IDs",
    "sender_id_request": "Sender ID KYC Upload",
    "upload_kyc_documents": "Upload your KYC documents to request a custom sender ID",
    "sender_name": "Requested Sender ID",
    "sample_message": "Sample Message Content",
    "submission_successful": "Submission Successful!",
    "status.active": "Active",
    "status.pending": "Pending",
    "status.failed": "Failed",
    "status.sending": "Sending",
    "status.scheduled": "Scheduled",
    "dashboard.performance.title": "Performance Overview",
    "dashboard.performance.data.real": "Real Data",
    "dashboard.performance.data.loading": "Loading...",
    "dashboard.performance.chart.bar": "Bar",
    "dashboard.performance.chart.line": "Line",
    "dashboard.performance.chart.pie": "Pie",
    "dashboard.performance.chart.loading_title": "Loading chart data...",
    "dashboard.performance.chart.loading_subtitle": "Fetching real-time data from database",
    "dashboard.performance.chart.empty_title": "No chart yet",
    "dashboard.performance.chart.empty_subtitle": "Start sending messages to see your performance data",
    "dashboard.performance.chart.empty_pie_subtitle": "Try switching to bar or line chart, or start sending messages",
    "dashboard.performance.chart.empty_trend_subtitle": "Start sending messages to see your performance trends",
    "dashboard.performance.summary": "Total Messages: {{total}} | Delivery Rate: {{rate}}%",
    "dashboard.performance.summary_loading": "Loading performance data...",
    "dashboard.performance.message_volume": "Message Volume",
    "dashboard.performance.delivery_rate": "Delivery Rate",
    "dashboard.empty.no_messages": "No messages yet",
    "dashboard.empty.no_contacts": "Add contacts to start",
    "dashboard.empty.no_campaigns": "Create a campaign",
    "dashboard.empty.no_credits": "Purchase credits",
    "dashboard.empty.no_sender_ids": "Request a sender ID",
    "dashboard.empty.no_activity": "No activity yet",
    "dashboard.empty.no_data": "No data available",
    "purchase_sms_credits": "Purchase SMS Credits",
    "top_up_account": "Top up your account to send more messages",
    "current_balance": "Current Balance",
    "choose_package": "Choose a Package",
    "enter_custom_amount": "Or Enter Custom Amount",
    "min_purchase_required": "Minimum 1000 credits required",
    "total_cost": "Total Cost",
    "calculating": "Calculating...",
    "base_credits_from_package": "Base credits from selected package. Click to edit and customize.",
    "select_payment_method": "Payment Details",
    "credits": "credits",
    "email_address": "Email Address",
    "receipt_and_confirmation": "We'll send you a receipt and payment confirmation",
    "full_name": "Full Name",
    "full_name_account": "Your full name as it appears on your mobile money account",
    "proceed_to_payment": "Proceed to Payment",
    "payment_in_progress": "Payment in Progress",
    "confirm_purchase": "Confirm Purchase",
    "complete_payment_mobile": "Please complete the payment on your mobile device",
    "review_order": "Review your order before proceeding",
    "total_amount": "Total Amount",
    "mobile_money_payment": "Mobile Money Payment",
    "your_mobile_number": "Your Mobile Number",
    "instructions": "Instructions",
    "payment_instructions_text": "After confirming payment, you'll receive a mobile money prompt on your phone. Complete the payment to add SMS credits to your account.",
    "cancel": "Cancel",
    "processing": "Processing...",
    "confirm_payment": "Confirm Payment",
    "close": "Close",
    "package": "Package",
    "sms_credits": "SMS Credits",
    "payment_method": "Payment Method",
    "enter_phone_number_mobile_money": "Enter the phone number associated with your mobile money account",
    "contacts": "Contacts",
    "manage_customer_database": "Manage your customer database and relationships",
    "phone_number": "Phone Number",
    "tags": "Tags",
    "select_tags": "Select Tags",
    "additional_info": "Additional Info",
    "total": "total",
    "no_contacts_selected": "No contacts selected",
    "please_select_contacts": "Please select contacts",
    "enter_name": "Enter Name",
    "add_contact": "Add Contact",
    "export_contacts": "Export Contacts",
    "import_contacts": "Import Contacts",
    "delete_contacts": "Delete Contacts",
    "edit_contacts": "Edit Contacts",
    "add_tags": "Add Tags",
    "purchase_history": "Purchase History",
    "sender_names": "Sender Names",
    "integration_guide": "Integration Guide",
    "transaction_id": "Transaction ID",
    "amount": "Amount",
    "status": "Status",
    "date": "Date",
    "sender_id": "Sender ID",
    "approved": "Approved",
    "pending": "Pending",
    "rejected": "Rejected",
    "manage_sender_ids": "Manage your registered sender IDs for SMS campaigns",
    "loading_sender_names": "Loading sender names...",
    "no_sender_names": "No sender names available",
    "unable_load_sender_names": "Unable to load sender names. Please try again or contact support.",
    "error_loading_sender_names": "Error loading sender names",
    "sender_names.payment.title": "Payment Processing",
    "sender_names.payment.waiting": "Waiting for payment confirmation...",
    "sender_names.payment.instruction": "A payment request has been sent to your mobile device. Please authorize the transaction using your PIN",
    "sender_names.payment.order_id": "Order ID",
    "sender_names.payment.amount": "Amount",
    "sender_names.payment.after_approval": "After approval",
    "sender_names.payment.finalize_click": "click “Payment Complete” to finalize.",
    "sender_names.payment.copy_order_id": "Copy Order ID",
    "sender_names.payment.complete": "Payment Complete",
    "sender_names.payment.checking_status": "Checking payment status...",
    "common.copied": "Copied",
    "common.order_id_copied": "Order ID copied",
    "loading_transactions": "Loading transactions...",
    "no_transactions": "No transactions found",
    "integration_documentation": "API Documentation",
    "api_reference": "API Reference",
    "quick_start": "Quick Start",
    "get_api_key": "Get Your API Key",
    "send_first_sms": "Send Your First SMS",
    "check_balance": "Check Your Balance",
    "view_all_credit_purchases": "View all your SMS credit purchases and transactions",
    "transaction_details": "Transaction Details",
    "integration.quick_start_requests": "Quick Start Requests (cURL)",
    "integration.python_examples": "Python Examples - Partner Integration",
    "integration.endpoints": "Endpoints",
    "integration.get_credit_balance_single": "Get Credit Balance (Single Tenant)",
    "integration.get_balance_for_specific": "Get balance for a specific tenant",
    "integration.get_credit_balance_all": "Get Credit Balance (All Clients)",
    "integration.get_balance_for_all": "Get balance for all clients",
    "integration.send_sms": "Send Your First SMS",
    "integration.fire_production_request": "Fire a production request with a JSON payload and bearer token.",
    "integration.check_balance": "Check Your Balance",
    "integration.confirm_remaining": "Confirm remaining SMS credits for the authenticated account.",
    "integration.get_single_tenant": "Get Credit Balance (Single Tenant)",
    "integration.get_partner_integration": "Get credit balance for a specific tenant using Partner integration.",
    "integration.get_all_clients": "Get Credit Balance (All Clients)",
    "integration.get_all_clients_partner": "Get credit balance for all clients using Partner integration.",
    "integration.get_sms_usage_single": "Get SMS Usage by User (Single Tenant)",
    "integration.get_sms_usage_stats": "Get SMS usage statistics for a specific tenant.",
    "integration.get_sms_usage_all": "Get SMS Usage by User (All Tenants)",
    "integration.get_sms_usage_all_stats": "Get SMS usage statistics for all tenants.",
    "integration.authentication": "Authentication",
    "integration.endpoints_label": "Endpoints",
    "integration.quick_reference": "Quick Reference",
    "integration.base_url": "Base URL",
    "integration.support": "Support",
    "integration.email": "Email",
    "integration.dashboard_link": "Dashboard",
    "integration.version": "Version 1.3 · Last updated November 15, 2025 · Production-ready.",
    "integration.step": "Step {{step}}",
  },
  sw: {
    "app.name": "SENDA",
    "app.tagline": "Kituo cha Mawasiliano",
    "tutorial.title": "Karibu SENDA",
    "tutorial.description": "Tazama video hii fupi ya mafunzo ili kuanza kutumia mfumo wetu.",
    "nav.dashboard": "Dashibodi",
    "nav.sms": "SMS",
    "nav.send_sms": "Tuma SMS",
    "nav.purchase_sms": "Nunua SMS",
    "nav.sender_names": "Majina ya Mtumaji",
    "nav.purchase_history": "Historia ya Ununuzi",
    "nav.contacts": "Anwani",
    "nav.campaigns": "Kampeni",
    "nav.partner_insights": "Maarifa ya Mshirika",
    "nav.integration_guide": "Mwongozo wa Ujumuishaji",
    "nav.partner_reference": "Rejea ya Mshirika",
    "nav.settings": "Mipangilio",
    "nav.messaging": "Ujumbe",
    "nav.ai_copilots": "Wasaidizi wa AI",
    "nav.voice_copilots": "Wasaidizi wa Sauti",
    "nav.voice_ivr": "Simu na IVR",
    "nav.ivr_flows": "Mtiririko wa IVR",
    "nav.phone_numbers": "Namba za Simu",
    "nav.calls": "Simu",
    "nav.recordings": "Rekodi za Simu",
    "nav.audio_prompts": "Sauti za Mfumo",
    "nav.voice_agents": "Wakala",
    "nav.ai_call_intelligence": "Uchambuzi wa AI wa Simu",
    "voice.overview.subtitle": "Kila kitu cha kutengeneza na kuendesha huduma za simu.",
    "voice.overview.ivr_flows_desc": "Tengeneza na uchapishe mitiririko ya simu — menyu, uhamishaji, saa za kazi, ujumbe wa sauti.",
    "voice.overview.phone_numbers_desc": "Unganisha kila namba na mtiririko mmoja uliochapishwa.",
    "voice.overview.calls_desc": "Angalia simu zilizoingia na zilizotoka, matokeo yake, na hatua za mtiririko.",
    "voice.overview.recordings_desc": "Kila simu na ujumbe wa sauti uliorekodiwa, kwenye orodha moja.",
    "voice.overview.ai_settings_desc": "Washa muhtasari, hisia, na sababu ya kupiga simu baada ya kila simu.",
    "common.try_again": "Jaribu tena",
    "voice.calls.tab_all": "Zote",
    "voice.calls.tab_inbound": "Zilizoingia",
    "voice.calls.tab_outbound": "Zilizotoka",
    "voice.calls.tab_missed": "Zilizokosa",
    "voice.calls.range_7": "Siku 7",
    "voice.calls.range_30": "Siku 30",
    "voice.calls.range_90": "Siku 90",
    "voice.calls.range_all": "Zote",
    "voice.calls.range_group_label": "Muda",
    "voice.calls.loading": "Inapakia…",
    "voice.calls.count_subtitle": "Simu {{count}}, zimerekodiwa na zinaweza kutafutwa",
    "voice.calls.search_placeholder": "Tafuta mpiga simu, mada, maandishi ya mazungumzo…",
    "voice.calls.search_aria": "Tafuta simu",
    "voice.calls.agent_aria": "Wakala",
    "voice.calls.all_agents": "Wakala wote",
    "voice.calls.sentiment_aria": "Hisia",
    "voice.calls.any_sentiment": "Hisia zote",
    "voice.calls.sentiment_positive": "Chanya",
    "voice.calls.sentiment_neutral": "Wastani",
    "voice.calls.sentiment_negative": "Hasi",
    "voice.calls.no_match_title": "Hakuna simu zinazolingana",
    "voice.calls.no_calls_title": "Bado hakuna simu",
    "voice.calls.no_match_desc": "Jaribu kichujio kingine au muda mrefu zaidi.",
    "voice.calls.no_calls_desc": "Simu halisi zitakazoingia au kutoka zitaonekana hapa.",
    "voice.calls.col_caller": "Mpiga simu",
    "voice.calls.col_agent": "Wakala",
    "voice.calls.col_time": "Muda",
    "voice.calls.col_length": "Urefu",
    "voice.calls.col_ai_summary": "Muhtasari wa AI",
    "voice.calls.col_sentiment": "Hisia",
    "voice.calls.no_recording": "Hakuna rekodi",
    "voice.calls.outbound_call": "Simu iliyotoka",
    "voice.calls.inbound_call": "Simu iliyoingia",
    "voice.calls.details": "Taarifa",
    "voice.calls.from": "Kutoka",
    "voice.calls.to": "Kwenda",
    "voice.calls.outcome": "Matokeo",
    "voice.calls.recording": "Rekodi",
    "voice.calls.stored": "ilihifadhiwa",
    "voice.calls.no_recording_for_call": "Hakuna rekodi kwa simu hii.",
    "voice.calls.other_recordings": "Rekodi nyingine za simu hii",
    "voice.calls.transcript": "Maandishi ya mazungumzo",
    "voice.calls.journey": "Mwenendo wa simu",
    "voice.calls.load_more": "Pakia zaidi",
    "voice.calls.error_loading": "Imeshindikana kupakia orodha ya simu",
    "voice.calls.outcome_completed": "Imekamilika",
    "voice.calls.outcome_failed": "Haikufanikiwa",
    "voice.calls.outcome_busy": "Namba ilikuwa na mazungumzo",
    "voice.calls.outcome_no_answer": "Hakujibiwa",
    "voice.calls.outcome_aborted": "Ilisitishwa",
    "voice.calls.outcome_rejected": "Ilikataliwa",
    "voice.calls.outcome_cancelled": "Ilighairiwa",
    "voice.calls.outcome_technical_failure": "Hitilafu ya mtandao",
    "voice.calls.outcome_ringing": "Inaita…",
    "voice.calls.outcome_in_progress": "Inaendelea…",
    "voice.recordings.count_subtitle": "Rekodi {{count}} zimehifadhiwa",
    "voice.recordings.search_placeholder": "Tafuta mpiga simu, namba, wakala…",
    "voice.recordings.search_aria": "Tafuta rekodi",
    "voice.recordings.error_loading": "Imeshindikana kupakia rekodi",
    "voice.recordings.no_match_title": "Hakuna kinacholingana",
    "voice.recordings.no_recordings_title": "Bado hakuna rekodi",
    "voice.recordings.no_match_desc": "Jaribu namba au wakala mwingine.",
    "voice.recordings.no_recordings_desc": "Rekodi zitaonekana hapa mara simu itakaporekodiwa au mpiga simu ataacha ujumbe.",
    "voice.recordings.col_number": "Namba",
    "voice.recordings.col_size": "Ukubwa",
    "voice.recordings.col_stored": "Ilihifadhiwa",
    "voice.recordings.col_actions": "Vitendo",
    "common.try_again_desc": "Tafadhali jaribu tena.",
    "voice.ai_settings.error_loading": "Imeshindikana kupakia mipangilio ya AI",
    "voice.ai_settings.save_failed": "Imeshindikana kuhifadhi",
    "voice.ai_settings.enabled_toast_title": "AI Call Analysis imewashwa",
    "voice.ai_settings.enabled_toast_desc": "Uchambuzi wa AI umewashwa kwa simu zako.",
    "voice.ai_settings.language_auto": "Itambue lugha yenyewe (auto)",
    "voice.ai_settings.language_sw": "Kiswahili",
    "voice.ai_settings.language_en": "Kiingereza",
    "voice.ai_settings.toggle_summary": "Muhtasari wa simu",
    "voice.ai_settings.toggle_sentiment": "Hisia za mteja",
    "voice.ai_settings.toggle_intent": "Sababu ya kupiga simu",
    "voice.ai_settings.toggle_categorization": "Mada na uainishaji",
    "voice.ai_settings.subtitle": "Uchambuzi wa AI wa simu zako — hiari, umezimwa kwa default, na haihusiani na mfumo wa IVR.",
    "voice.ai_settings.enabled_desc": "AI inaweza kuchanganua mazungumzo ya simu ili kukusaidia kuelewa mahitaji ya wateja na kuboresha huduma.",
    "voice.ai_settings.disabled_desc": "Uchambuzi wa AI umezimwa. Hakuna uchambuzi wa AI utakaofanywa kwenye simu zako.",
    "voice.ai_settings.consent_text": "SENDA itatumia maudhui ya mazungumzo kuchanganua simu na kutoa muhtasari pamoja na taarifa muhimu za huduma kwa wateja.",
    "voice.ai_settings.toggles_title": "Chagua unachotaka kuchambuliwa",
    "voice.ai_settings.toggles_desc": "Kila kipengele kinaweza kuzimwa peke yake, bila kuzima uchambuzi wa AI kwa ujumla.",
    "voice.ai_settings.transcription_language_label": "Lugha ya kuandika mazungumzo",
    "voice.ai_settings.realtime_label": "Uchambuzi wa Papo Hapo",
    "voice.ai_settings.realtime_tooltip": "Inahitaji njia ya simu inayotuma sauti moja kwa moja wakati wa mazungumzo — haipatikani kwa sasa.",
    "voice.ai_settings.realtime_unavailable": "Haipatikani",
    "voice.numbers.error_loading": "Imeshindikana kupakia namba za simu",
    "voice.numbers.created_toast_title": "Namba imeongezwa",
    "voice.numbers.created_toast_desc": "Sasa unaweza kuiunganisha na mtiririko wa IVR.",
    "voice.numbers.create_failed": "Imeshindikana kuongeza namba",
    "voice.numbers.flow_connected_title": "Mtiririko umeunganishwa",
    "voice.numbers.flow_connected_desc": "Namba hii sasa inatumia mtiririko uliochagua.",
    "voice.numbers.update_failed": "Imeshindikana kusasisha",
    "voice.numbers.number_saved": "Namba imehifadhiwa",
    "voice.numbers.save_number_failed": "Imeshindikana kuhifadhi namba",
    "voice.numbers.recording_on_title": "Inarekodi kila mazungumzo",
    "voice.numbers.recording_off_title": "Kurekodi kumezimwa",
    "voice.numbers.recording_on_desc": "Kila simu inayotumwa kwa wakala kwenye namba hii sasa itarekodiwa.",
    "voice.numbers.recording_off_desc": "Simu zitarekodiwa tu pale mtiririko unapohitaji hivyo waziwazi.",
    "voice.numbers.disconnect_confirm": "Tenganisha \"{{flow}}\" na {{number}}? Simu za namba hii hazitajibiwa mpaka uunganishe mtiririko mwingine.",
    "voice.numbers.this_number": "namba hii",
    "voice.numbers.copied_title": "Imenakiliwa",
    "voice.numbers.copied_desc": "Webhook URL imenakiliwa.",
    "voice.numbers.subtitle": "Unganisha kila namba na mtiririko mmoja uliochapishwa — ndio utakaotumika mtu anapopiga.",
    "voice.numbers.add_number": "Ongeza namba",
    "voice.numbers.add_number_title": "Ongeza namba mpya",
    "voice.numbers.add_number_desc": "Weka namba yako — huhitaji mtoa huduma (provider) au mtiririko kuanza; unaweza kuviunganisha baadaye.",
    "voice.numbers.phone_label": "Namba ya simu",
    "voice.numbers.display_name_label": "Jina la kutambulisha (hiari)",
    "voice.numbers.display_name_placeholder": "k.m. Huduma kwa Wateja",
    "voice.numbers.cancel": "Ghairi",
    "voice.numbers.creating": "Inaongeza…",
    "voice.numbers.save_number": "Hifadhi namba",
    "voice.numbers.empty_title": "Bado hakuna namba",
    "voice.numbers.empty_desc": "Ongeza namba yako ya simu ili uanze kuipangia mtiririko wa IVR.",
    "voice.numbers.provider_none": "Bila mtoa huduma",
    "voice.numbers.status_active": "Hai",
    "voice.numbers.status_inactive": "Imezimwa",
    "voice.numbers.no_provider_notice": "Namba imeongezwa lakini bado haijaunganishwa na mtoa huduma (provider) — wasiliana na SENDA ili simu ziweze kuanza kupokelewa.",
    "voice.numbers.active_flow_label": "Mtiririko unaotumika",
    "voice.numbers.flow_connected_suffix": "imeunganishwa — hii ndiyo inayotumika kwa kila simu ya {{number}}.",
    "voice.numbers.disconnect": "Tenganisha",
    "voice.numbers.no_flow_connected": "Hakuna mtiririko uliounganishwa",
    "voice.numbers.connect_flow_placeholder": "Unganisha mtiririko…",
    "voice.numbers.no_flows_prefix": "Bado hakuna mtiririko uliochapishwa —",
    "voice.numbers.no_flows_link": "chapisha mmoja kwanza",
    "voice.numbers.webhook_label": "Webhook URL (bandika kwenye sehemu ya callback URL ya mtoa huduma wako)",
    "voice.numbers.record_title": "Rekodi kila mazungumzo",
    "voice.numbers.record_desc": "Inarekodi kiotomatiki kila simu inayotumwa kwa wakala kwenye namba hii.",
    "voice.numbers.edit_flow_prefix": "Hariri",
    "voice.access.title": "Unahitaji Ruhusa ya Simu na IVR",
    "voice.access.desc": "Bado huna ruhusa ya kufikia Simu na IVR. Muulize msimamizi wa akaunti au timu ya SENDA akuwashie kipengele hiki.",
    "voice.plan.no_feature": "Kifurushi chako hakina kipengele cha Simu na IVR.",
    "voice.ivr.error_loading": "Imeshindikana kupakia mitiririko",
    "voice.ivr.error_loading_flow": "Imeshindikana kupakia mtiririko",
    "action.buy_sms_credits": "Nunua Salio la SMS",
    "profile.profile": "Wasifu",
    "profile.settings": "Mipangilio",
    "profile.logout": "Toka",
    "status.online": "Mtandaoni",
    "theme.toggle": "Badili Mandhari",
    "user.loading": "Inapakia...",
    "user.user": "Mtumiaji",
    "user.no_email": "Hakuna barua pepe",
    "settings.language": "Lugha",
    "dashboard.welcome": "Karibu tena 👋",
    "dashboard.subtitle": "Fuatilia utendaji wa jukwaa lako la mawasiliano kwa wakati halisi.",
    "dashboard.metric.total_messages": "Jumla ya Ujumbe",
    "dashboard.metric.last_30_days": "Siku 30 zilizopita",
    "dashboard.metric.active_contacts": "Anwani Hai",
    "dashboard.metric.engaged_this_month": "Waliohusika mwezi huu",
    "dashboard.metric.campaign_success": "Mafanikio ya Kampeni",
    "dashboard.metric.delivery_rate": "Kiwango cha uwasilishaji",
    "dashboard.metric.sender_id": "Kitambulisho cha Mtumaji",
    "dashboard.metric.approved_sender_names": "Majina ya watumaji yaliyoidhinishwa",
    "dashboard.metric.current_credits": "Mikakati Sasa",
    "dashboard.metric.available_credits": "Mikakati inayopatikana",
    "dashboard.error.title": "Hitilafu ya Dashibodi",
    "dashboard.error.description": "Kulikuwa na hitilafu katika kupakia dashibodi.",
    "dashboard.error.hint": "Angalia konsoli kwa maelezo zaidi.",
    "dashboard.activity.title": "Shughuli za Hivi Karibuni",
    "dashboard.activity.live": "Moja kwa Moja",
    "dashboard.activity.none": "Hakuna shughuli za hivi karibuni",
    "dashboard.activity.view_all": "Tazama shughuli zote",
    "dashboard.quick_actions.title": "Vitendo vya Haraka",
    "dashboard.quick_actions.send_message": "Tuma Ujumbe",
    "dashboard.quick_actions.send_message_desc": "WhatsApp au SMS ya haraka",
    "dashboard.quick_actions.add_campaign": "Ongeza Kampeni Mpya",
    "dashboard.quick_actions.add_campaign_desc": "Kampeni ya ujumbe wa wingi",
    "dashboard.quick_actions.add_contacts": "Ongeza Anwani",
    "dashboard.quick_actions.add_contacts_desc": "Leta kutoka faili au ongeza mwenyewe",
    "dashboard.quick_actions.add_sender_id": "Ongeza Sender ID",
    "dashboard.quick_actions.create_template_desc": "Kiolezo cha ujumbe",
    "dashboard.quick_actions.need_help": "Unahitaji msaada?",
    "dashboard.quick_actions.contact_support": "Wasiliana na Msaada →",
    "dashboard.quick_actions.view_tutorial": "Tazama Kuchimba",
    "dashboard.quick_actions.tutorial_description": "Tazama video ya kuchimba kuhusu jinsi ya kutumia SENDA",
    "dashboard.recent_campaigns.title": "Kampeni za Hivi Karibuni",
    "dashboard.recent_campaigns.view_all": "Tazama zote →",
    "dashboard.recent_campaigns.empty_title": "Bado hakuna kampeni",
    "dashboard.recent_campaigns.empty_subtitle": "Tengeneza kampeni yako ya kwanza ili kuanza",
    "dashboard.recent_campaigns.status.completed": "Imekamilika",
    "dashboard.recent_campaigns.status.sending": "Inatuma",
    "dashboard.recent_campaigns.status.scheduled": "Imeratibiwa",
    "dashboard.recent_campaigns.status.failed": "Imeshindwa",
    "dashboard.recent_campaigns.menu.view_details": "Tazama maelezo",
    "dashboard.recent_campaigns.menu.duplicate": "Nakili",
    "dashboard.recent_campaigns.menu.edit": "Hariri",
    "dashboard.recent_campaigns.progress": "Maendeleo",
    "dashboard.recent_campaigns.sent": "Imetumwa",
    "dashboard.recent_campaigns.delivered": "Imefika",
    "dashboard.recent_campaigns.opened": "Imefunguliwa",
    "dashboard.sender_ids.title": "Vitambulisho vya Mtumaji Hai",
    "dashboard.sender_ids.active": "Hai",
    "dashboard.sender_ids.table.sender_id": "Kitambulisho cha Mtumaji",
    "dashboard.sender_ids.table.status": "Hali",
    "dashboard.sender_ids.table.sample_content": "Maudhui ya Mfano",
    "dashboard.sender_ids.table.created": "Imetengenezwa",
    "dashboard.sender_ids.empty_title": "Hakuna vitambulisho vya mtumaji",
    "dashboard.sender_ids.empty_subtitle": "Vitambulisho vitaonekana hapa baada ya kuidhinishwa",
    "dashboard.sender_ids.manage": "Simamia vitambulisho vya mtumaji",
    "status.active": "Hai",
    "status.pending": "Inasubiri",
    "status.failed": "Imeshindwa",
    "status.sending": "Inatuma",
    "status.scheduled": "Imeratibiwa",
    "dashboard.performance.title": "Muhtasari wa Utendaji",
    "dashboard.performance.data.real": "Data Halisi",
    "dashboard.performance.data.loading": "Inapakia...",
    "dashboard.performance.chart.bar": "Nguzo",
    "dashboard.performance.chart.line": "Mstari",
    "dashboard.performance.chart.pie": "Mviringo",
    "dashboard.performance.chart.loading_title": "Inapakia data ya chati...",
    "dashboard.performance.chart.loading_subtitle": "Inachukua data ya wakati halisi kutoka hifadhidata",
    "dashboard.performance.chart.empty_title": "Hakuna chati bado",
    "dashboard.performance.chart.empty_subtitle": "Anza kutuma ujumbe kuona data ya utendaji",
    "dashboard.performance.chart.empty_pie_subtitle": "Jaribu kubadilisha hadi chati ya nguzo au mstari, au anza kutuma ujumbe",
    "dashboard.performance.chart.empty_trend_subtitle": "Anza kutuma ujumbe kuona mwenendo wa utendaji",
    "dashboard.performance.summary": "Jumla ya Ujumbe: {{total}} | Kiwango cha Uwasilishaji: {{rate}}%",
    "dashboard.performance.summary_loading": "Inapakia data ya utendaji...",
    "dashboard.performance.message_volume": "Kiasi cha Ujumbe",
    "dashboard.performance.delivery_rate": "Kiwango cha Uwasilishaji",
    "dashboard.empty.no_messages": "Hakuna ujumbe bado",
    "dashboard.empty.no_contacts": "Ongeza anwani kuanza",
    "dashboard.empty.no_campaigns": "Tengeneza kampeni",
    "dashboard.empty.no_credits": "Nunua salio",
    "dashboard.empty.no_sender_ids": "Omba kitambulisho cha mtumaji",
    "dashboard.empty.no_activity": "Hakuna shughuli bado",
    "dashboard.empty.no_data": "Hakuna data",
    "sender_id_request": "Upakaji wa KYC wa Kitambulisho cha Mtumaji",
    "upload_kyc_documents": "Pakia nyaraka zako za KYC ili kuomba kitambulisho cha mtumaji cha kawaida",
    "sender_name": "Kitambulisho cha Mtumaji Kilicho Omwa",
    "sample_message": "Mfano wa Ujumbe",
    "submission_successful": "Uwasilishaji Umefanikiwa!",
    "purchase_sms_credits": "Nunua Salio la SMS",
    "top_up_account": "Jaza akaunti yako ili kutuma ujumbe zaidi",
    "current_balance": "Salio Lako la Sasa",
    "choose_package": "Chagua Paketi",
    "enter_custom_amount": "Au Ingiza Kiasi Cha Kiadhari",
    "min_purchase_required": "Kima cha chini cha salio 1000 kinahitajika",
    "total_cost": "Jumla ya Gharama",
    "calculating": "Inahesabu...",
    "base_credits_from_package": "Salio la msingi kutoka paketi iliyochaguliwa. Bofya ili kuhariri na kukamatia.",
    "select_payment_method": "Maelezo ya Malipo",
    "credits": "salio",
    "email_address": "Anwani ya Barua Pepe",
    "receipt_and_confirmation": "Tutakupigia risiti na uthibitisho wa malipo",
    "full_name": "Jina Kamili",
    "full_name_account": "Jina lako kamili kama linavyoonekana kwenye akaunti yako ya pesa za simu",
    "proceed_to_payment": "Endelea na Kulipa",
    "payment_in_progress": "Malipo Yanayoendelea",
    "confirm_purchase": "Thibitisha Ununuzi",
    "complete_payment_mobile": "Tafadhali kamili malipo kwenye simu yako",
    "review_order": "Kagua agizo lako kabla ya kuendelea",
    "total_amount": "Jumla ya Kiasi",
    "mobile_money_payment": "Malipo ya Pesa za Simu",
    "your_mobile_number": "Namba Yako ya Simu",
    "instructions": "Maelezo",
    "payment_instructions_text": "Baada ya kuthibitisha malipo, utapokea onyo wa pesa za simu kwenye simu yako. Kamili malipo ili kuongeza salio la SMS kwenye akaunti yako.",
    "cancel": "Ghairi",
    "processing": "Inaproceed...",
    "confirm_payment": "Thibitisha Malipo",
    "close": "Funga",
    "package": "Paketi",
    "sms_credits": "Salio la SMS",
    "payment_method": "Njia ya Kulipa",
    "enter_phone_number_mobile_money": "Ingiza namba ya simu iliyohusika na akaunti yako ya pesa za simu",
    "contacts": "Wasilianaji",
    "manage_customer_database": "Dhibiti hifadhidata yako ya wakilishi na mahusiano",
    "phone_number": "Namba ya Simu",
    "tags": "Lebo",
    "select_tags": "Chagua Lebo",
    "additional_info": "Taarifa Nyingine",
    "total": "jumla",
    "no_contacts_selected": "Hakuna wasilianaji waliochaguliwa",
    "please_select_contacts": "Tafadhali chagua wasilianaji",
    "enter_name": "Ingiza Jina",
    "add_contact": "Ongeza Wasilianaji",
    "export_contacts": "Eksport Wasilianaji",
    "import_contacts": "Ingiza Wasilianaji",
    "delete_contacts": "Futa Wasilianaji",
    "edit_contacts": "Hariri Wasilianaji",
    "add_tags": "Ongeza Lebo",
    "purchase_history": "Historia ya Ununuzi",
    "sender_names": "Majina ya Mtumaji",
    "integration_guide": "Mwongozo wa Ujumuishaji",
    "transaction_id": "Kitambulisho cha Muamala",
    "amount": "Kiasi",
    "status": "Hali",
    "date": "Tarehe",
    "sender_id": "Kitambulisho cha Mtumaji",
    "approved": "Imeidhinishwa",
    "pending": "Inasubiri",
    "rejected": "Ilikataliwa",
    "manage_sender_ids": "Simamia vitambulisho vyako vya mtumaji vilivoandikishwa kwa kampeni za SMS",
    "loading_sender_names": "Inapakia majina ya mtumaji...",
    "no_sender_names": "Hakuna majina ya mtumaji yanayopatikana",
    "unable_load_sender_names": "Haiwezi kupakia majina ya mtumaji. Tafadhali jaribu tena au wasiliana na msaada.",
    "error_loading_sender_names": "Kosa katika kupakia majina ya mtumaji",
    "sender_names.payment.title": "Malipo Yanashughulikiwa",
    "sender_names.payment.waiting": "Inasubiri uthibitisho wa malipo...",
    "sender_names.payment.instruction": "Ombi la malipo limetumwa kwenye simu yako. Tafadhali thibitisha muamala kwa kutumia PIN yako",
    "sender_names.payment.order_id": "Nambari ya Agizo",
    "sender_names.payment.amount": "Kiasi",
    "sender_names.payment.after_approval": "Baada ya kuidhinisha",
    "sender_names.payment.finalize_click": "bonyeza “Malipo Yamekamilika” ili kukamilisha.",
    "sender_names.payment.copy_order_id": "Nakili Nambari ya Agizo",
    "sender_names.payment.complete": "Malipo Yamekamilika",
    "sender_names.payment.checking_status": "Inakagua hali ya malipo...",
    "common.copied": "Imenakiliwa",
    "common.order_id_copied": "Nambari ya Agizo imenakiliwa",
    "loading_transactions": "Inapakia muamala...",
    "no_transactions": "Hakuna muamala iliyopatikana",
    "integration_documentation": "Nyaraka za API",
    "api_reference": "Rejea ya API",
    "quick_start": "Haraka Kuanza",
    "get_api_key": "Pata Ufunguo Wako wa API",
    "send_first_sms": "Tuma SMS Yako ya Kwanza",
    "check_balance": "Angalia Salio Lako",
    "view_all_credit_purchases": "Tazama ununuzi wako wote wa salio la SMS na muamala",
    "transaction_details": "Maelezo ya Muamala",
    "integration.quick_start_requests": "Ombi za Haraka Kuanza (cURL)",
    "integration.python_examples": "Mifano ya Python - Ujumuishaji wa Mshirika",
    "integration.endpoints": "Ncha za API",
    "integration.get_credit_balance_single": "Pata Salio la Salio (Mtenants Mmoja)",
    "integration.get_balance_for_specific": "Pata salio kwa mtenants mahsusi",
    "integration.get_credit_balance_all": "Pata Salio la Salio (Wateja Wote)",
    "integration.get_balance_for_all": "Pata salio kwa wateja wote",
    "integration.send_sms": "Tuma SMS Yako ya Kwanza",
    "integration.fire_production_request": "Utumie ombi la uzalishaji na payload ya JSON na ishara ya kubeba.",
    "integration.check_balance": "Angalia Salio Lako",
    "integration.confirm_remaining": "Thibitisha salio la SMS lililobaki kwa akaunti iliyoonekanika.",
    "integration.get_single_tenant": "Pata Salio la Salio (Mtenants Mmoja)",
    "integration.get_partner_integration": "Pata salio kwa mtenants mahsusi kwa kutumia ujumuishaji wa Mshirika.",
    "integration.get_all_clients": "Pata Salio la Salio (Wateja Wote)",
    "integration.get_all_clients_partner": "Pata salio kwa wateja wote kwa kutumia ujumuishaji wa Mshirika.",
    "integration.get_sms_usage_single": "Pata Utumiaji wa SMS na Mtumiaji (Mtenants Mmoja)",
    "integration.get_sms_usage_stats": "Pata takwimu za utumiaji wa SMS kwa mtenants mahsusi.",
    "integration.get_sms_usage_all": "Pata Utumiaji wa SMS na Mtumiaji (Mtenants Yote)",
    "integration.get_sms_usage_all_stats": "Pata takwimu za utumiaji wa SMS kwa mtenants yote.",
    "integration.authentication": "Uthibitisho",
    "integration.endpoints_label": "Ncha za API",
    "integration.quick_reference": "Rejea ya Haraka",
    "integration.base_url": "URL ya Msingi",
    "integration.support": "Msaada",
    "integration.email": "Barua Pepe",
    "integration.dashboard_link": "Dashibodi",
    "integration.version": "Toleo 1.3 · Ilibadilishwa Novemba 15, 2025 · Tayari kwa Uzalishaji.",
    "integration.step": "Hatua {{step}}",
  },
} as const;

type LanguageCode = keyof typeof translations;

type LanguageContextValue = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  t: (key: keyof typeof translations.en, params?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export { LanguageContext };

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    // Check both localStorage keys for backwards compatibility
    const storedPreference = typeof window !== "undefined" ? localStorage.getItem("language-preference") : null;
    const storedLegacy = typeof window !== "undefined" ? localStorage.getItem("language") : null;
    const stored = storedPreference || storedLegacy;

    if (stored === "sw" || stored === "en") {
      return stored;
    }
    // Default to English if no preference
    return "en";
  });

  const setLanguage = (nextLanguage: LanguageCode) => {
    setLanguageState(nextLanguage);
    if (typeof window !== "undefined") {
      // Store in preferred key
      localStorage.setItem("language-preference", nextLanguage);
      // Also update legacy key for backwards compatibility
      localStorage.setItem("language", nextLanguage);
    }
  };

  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = useMemo(() => {
    return (key: keyof typeof translations.en, params?: Record<string, string | number>) => {
      const base = translations[language]?.[key] || translations.en[key] || String(key);
      if (!params) {
        return base;
      }
      return Object.keys(params).reduce((result, paramKey) => {
        return result.replace(new RegExp(`{{${paramKey}}}`, "g"), String(params[paramKey]));
      }, base);
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
