import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  en: {
    "app.name": "Mifumo SMS",
    "app.tagline": "Communication Hub",
    "tutorial.title": "Welcome to Mifumo SMS",
    "tutorial.description": "Watch this quick tutorial to get started with our system.",
    "nav.dashboard": "Dashboard",
    "nav.sms": "SMS",
    "nav.send_sms": "Send SMS",
    "nav.purchase_sms": "Purchase SMS",
    "nav.sender_names": "Sender Names",
    "nav.purchase_history": "Purchase History",
    "nav.contacts": "Contacts",
    "nav.campaigns": "Campaigns",
    "nav.partner_insights": "Partner Insights",
    "nav.integration_guide": "Integration Guide",
    "nav.partner_reference": "Partner Reference",
    "nav.settings": "Settings",
    "action.buy_sms_credits": "Buy SMS Credits",
    "profile.profile": "Profile",
    "profile.settings": "Settings",
    "profile.logout": "Log out",
    "status.online": "Online",
    "theme.toggle": "Toggle theme",
    "user.loading": "Loading...",
    "user.user": "User",
    "user.no_email": "No email",
    "settings.language": "Language",
    "dashboard.welcome": "Welcome back 👋",
    "dashboard.subtitle": "Monitor your communication platform performance in real-time.",
    "dashboard.metric.total_messages": "Total Messages",
    "dashboard.metric.last_30_days": "Last 30 days",
    "dashboard.metric.active_contacts": "Active Contacts",
    "dashboard.metric.engaged_this_month": "Engaged this month",
    "dashboard.metric.campaign_success": "Campaign Success",
    "dashboard.metric.delivery_rate": "Delivery rate",
    "dashboard.metric.sender_id": "Sender ID",
    "dashboard.metric.approved_sender_names": "Approved sender names",
    "dashboard.error.title": "Dashboard Error",
    "dashboard.error.description": "There was an error loading the dashboard.",
    "dashboard.error.hint": "Check the console for more details.",
    "dashboard.activity.title": "Recent Activity",
    "dashboard.activity.live": "Live",
    "dashboard.activity.none": "No recent activity",
    "dashboard.activity.view_all": "View all activity",
    "dashboard.quick_actions.title": "Quick Actions",
    "dashboard.quick_actions.send_message": "Send Message",
    "dashboard.quick_actions.send_message_desc": "Quick WhatsApp or SMS",
    "dashboard.quick_actions.add_campaign": "Add New Campaign",
    "dashboard.quick_actions.add_campaign_desc": "Bulk messaging campaign",
    "dashboard.quick_actions.add_contacts": "Add Contacts",
    "dashboard.quick_actions.add_contacts_desc": "Import or add manually",
    "dashboard.quick_actions.create_template": "Create Template",
    "dashboard.quick_actions.create_template_desc": "Message template",
    "dashboard.quick_actions.need_help": "Need help?",
    "dashboard.quick_actions.contact_support": "Contact Support →",
    "dashboard.quick_actions.view_tutorial": "View Tutorial",
    "dashboard.quick_actions.tutorial_description": "Watch our video tutorial to learn how to use Mifumo SMS",
    "dashboard.recent_campaigns.title": "Recent Campaigns",
    "dashboard.recent_campaigns.view_all": "View all →",
    "dashboard.recent_campaigns.empty_title": "No campaigns yet",
    "dashboard.recent_campaigns.empty_subtitle": "Create your first campaign to get started",
    "dashboard.recent_campaigns.status.completed": "Completed",
    "dashboard.recent_campaigns.status.sending": "Sending",
    "dashboard.recent_campaigns.status.scheduled": "Scheduled",
    "dashboard.recent_campaigns.status.failed": "Failed",
    "dashboard.recent_campaigns.menu.view_details": "View details",
    "dashboard.recent_campaigns.menu.duplicate": "Duplicate",
    "dashboard.recent_campaigns.menu.edit": "Edit",
    "dashboard.recent_campaigns.progress": "Progress",
    "dashboard.recent_campaigns.sent": "Sent",
    "dashboard.recent_campaigns.delivered": "Delivered",
    "dashboard.recent_campaigns.opened": "Opened",
    "dashboard.sender_ids.title": "Active Sender IDs",
    "dashboard.sender_ids.active": "Active",
    "dashboard.sender_ids.table.sender_id": "Sender ID",
    "dashboard.sender_ids.table.status": "Status",
    "dashboard.sender_ids.table.sample_content": "Sample Content",
    "dashboard.sender_ids.table.created": "Created",
    "dashboard.sender_ids.empty_title": "No sender IDs found",
    "dashboard.sender_ids.empty_subtitle": "Sender IDs will appear here once they are approved",
    "dashboard.sender_ids.manage": "Manage sender IDs",
    "status.active": "Active",
    "status.pending": "Pending",
    "status.failed": "Failed",
    "status.sending": "Sending",
    "status.scheduled": "Scheduled",
    "dashboard.performance.title": "Performance Overview",
    "dashboard.performance.data.real": "Real Data",
    "dashboard.performance.data.loading": "Loading...",
    "dashboard.performance.chart.bar": "Bar",
    "dashboard.performance.chart.line": "Line",
    "dashboard.performance.chart.pie": "Pie",
    "dashboard.performance.chart.loading_title": "Loading chart data...",
    "dashboard.performance.chart.loading_subtitle": "Fetching real-time data from database",
    "dashboard.performance.chart.empty_title": "No chart yet",
    "dashboard.performance.chart.empty_subtitle": "Start sending messages to see your performance data",
    "dashboard.performance.chart.empty_pie_subtitle": "Try switching to bar or line chart, or start sending messages",
    "dashboard.performance.chart.empty_trend_subtitle": "Start sending messages to see your performance trends",
    "dashboard.performance.summary": "Total Messages: {{total}} | Delivery Rate: {{rate}}%",
    "dashboard.performance.summary_loading": "Loading performance data...",
    "dashboard.performance.message_volume": "Message Volume",
    "dashboard.performance.delivery_rate": "Delivery Rate",
    "dashboard.empty.no_messages": "No messages yet",
    "dashboard.empty.no_contacts": "Add contacts to start",
    "dashboard.empty.no_campaigns": "Create a campaign",
    "dashboard.empty.no_sender_ids": "Request a sender ID",
    "dashboard.empty.no_activity": "No activity yet",
    "dashboard.empty.no_data": "No data available",
    "purchase_sms_credits": "Purchase SMS Credits",
    "top_up_account": "Top up your account to send more messages",
    "current_balance": "Current Balance",
    "choose_package": "Choose a Package",
    "enter_custom_amount": "Or Enter Custom Amount",
    "total_cost": "Total Cost",
    "calculating": "Calculating...",
    "base_credits_from_package": "Base credits from selected package. Click to edit and customize.",
    "select_payment_method": "Select Payment Method",
    "credits": "credits",
    "email_address": "Email Address",
    "receipt_and_confirmation": "We'll send you a receipt and payment confirmation",
    "full_name": "Full Name",
    "full_name_account": "Your full name as it appears on your mobile money account",
    "proceed_to_payment": "Proceed to Payment",
    "payment_in_progress": "Payment in Progress",
    "confirm_purchase": "Confirm Purchase",
    "complete_payment_mobile": "Please complete the payment on your mobile device",
    "review_order": "Review your order before proceeding",
    "total_amount": "Total Amount",
    "mobile_money_payment": "Mobile Money Payment",
    "your_mobile_number": "Your Mobile Number",
    "instructions": "Instructions",
    "payment_instructions_text": "After confirming payment, you'll receive a mobile money prompt on your phone. Complete the payment to add SMS credits to your account.",
    "cancel": "Cancel",
    "processing": "Processing...",
    "confirm_payment": "Confirm Payment",
    "close": "Close",
    "package": "Package",
    "sms_credits": "SMS Credits",
    "payment_method": "Payment Method",
    "enter_phone_number_mobile_money": "Enter the phone number associated with your mobile money account",
    "contacts": "Contacts",
    "manage_customer_database": "Manage your customer database and relationships",
    "phone_number": "Phone Number",
    "tags": "Tags",
    "select_tags": "Select Tags",
    "additional_info": "Additional Info",
    "total": "total",
    "no_contacts_selected": "No contacts selected",
    "please_select_contacts": "Please select contacts",
    "enter_name": "Enter Name",
    "add_contact": "Add Contact",
    "export_contacts": "Export Contacts",
    "import_contacts": "Import Contacts",
    "delete_contacts": "Delete Contacts",
    "edit_contacts": "Edit Contacts",
    "add_tags": "Add Tags",
    "purchase_history": "Purchase History",
    "sender_names": "Sender Names",
    "integration_guide": "Integration Guide",
    "transaction_id": "Transaction ID",
    "amount": "Amount",
    "status": "Status",
    "date": "Date",
    "sender_id": "Sender ID",
    "approved": "Approved",
    "pending": "Pending",
    "rejected": "Rejected",
    "manage_sender_ids": "Manage your registered sender IDs for SMS campaigns",
    "loading_sender_names": "Loading sender names...",
    "no_sender_names": "No sender names available",
    "unable_load_sender_names": "Unable to load sender names. Please try again or contact support.",
    "error_loading_sender_names": "Error loading sender names",
    "loading_transactions": "Loading transactions...",
    "no_transactions": "No transactions found",
    "integration_documentation": "API Documentation",
    "api_reference": "API Reference",
    "quick_start": "Quick Start",
    "get_api_key": "Get Your API Key",
    "send_first_sms": "Send Your First SMS",
    "check_balance": "Check Your Balance",
    "view_all_credit_purchases": "View all your SMS credit purchases and transactions",
    "transaction_details": "Transaction Details",
    "integration.quick_start_requests": "Quick Start Requests (cURL)",
    "integration.python_examples": "Python Examples - Partner Integration",
    "integration.endpoints": "Endpoints",
    "integration.get_credit_balance_single": "Get Credit Balance (Single Tenant)",
    "integration.get_balance_for_specific": "Get balance for a specific tenant",
    "integration.get_credit_balance_all": "Get Credit Balance (All Clients)",
    "integration.get_balance_for_all": "Get balance for all clients",
    "integration.send_sms": "Send Your First SMS",
    "integration.fire_production_request": "Fire a production request with a JSON payload and bearer token.",
    "integration.check_balance": "Check Your Balance",
    "integration.confirm_remaining": "Confirm remaining SMS credits for the authenticated account.",
    "integration.get_single_tenant": "Get Credit Balance (Single Tenant)",
    "integration.get_partner_integration": "Get credit balance for a specific tenant using Partner integration.",
    "integration.get_all_clients": "Get Credit Balance (All Clients)",
    "integration.get_all_clients_partner": "Get credit balance for all clients using Partner integration.",
    "integration.get_sms_usage_single": "Get SMS Usage by User (Single Tenant)",
    "integration.get_sms_usage_stats": "Get SMS usage statistics for a specific tenant.",
    "integration.get_sms_usage_all": "Get SMS Usage by User (All Tenants)",
    "integration.get_sms_usage_all_stats": "Get SMS usage statistics for all tenants.",
    "integration.authentication": "Authentication",
    "integration.endpoints_label": "Endpoints",
    "integration.quick_reference": "Quick Reference",
    "integration.base_url": "Base URL",
    "integration.support": "Support",
    "integration.email": "Email",
    "integration.dashboard_link": "Dashboard",
    "integration.version": "Version 1.3 · Last updated November 15, 2025 · Production-ready.",
    "integration.step": "Step {{step}}",
  },
  sw: {
    "app.name": "Mifumo SMS",
    "app.tagline": "Kituo cha Mawasiliano",
    "tutorial.title": "Karibu Mifumo SMS",
    "tutorial.description": "Tazama video hii fupi ya mafunzo ili kuanza kutumia mfumo wetu.",
    "nav.dashboard": "Dashibodi",
    "nav.sms": "SMS",
    "nav.send_sms": "Tuma SMS",
    "nav.purchase_sms": "Nunua SMS",
    "nav.sender_names": "Majina ya Mtumaji",
    "nav.purchase_history": "Historia ya Ununuzi",
    "nav.contacts": "Anwani",
    "nav.campaigns": "Kampeni",
    "nav.partner_insights": "Maarifa ya Mshirika",
    "nav.integration_guide": "Mwongozo wa Ujumuishaji",
    "nav.partner_reference": "Rejea ya Mshirika",
    "nav.settings": "Mipangilio",
    "action.buy_sms_credits": "Nunua Salio la SMS",
    "profile.profile": "Wasifu",
    "profile.settings": "Mipangilio",
    "profile.logout": "Toka",
    "status.online": "Mtandaoni",
    "theme.toggle": "Badili Mandhari",
    "user.loading": "Inapakia...",
    "user.user": "Mtumiaji",
    "user.no_email": "Hakuna barua pepe",
    "settings.language": "Lugha",
    "dashboard.welcome": "Karibu tena 👋",
    "dashboard.subtitle": "Fuatilia utendaji wa jukwaa lako la mawasiliano kwa wakati halisi.",
    "dashboard.metric.total_messages": "Jumla ya Ujumbe",
    "dashboard.metric.last_30_days": "Siku 30 zilizopita",
    "dashboard.metric.active_contacts": "Anwani Hai",
    "dashboard.metric.engaged_this_month": "Waliohusika mwezi huu",
    "dashboard.metric.campaign_success": "Mafanikio ya Kampeni",
    "dashboard.metric.delivery_rate": "Kiwango cha uwasilishaji",
    "dashboard.metric.sender_id": "Kitambulisho cha Mtumaji",
    "dashboard.metric.approved_sender_names": "Majina ya watumaji yaliyoidhinishwa",
    "dashboard.error.title": "Hitilafu ya Dashibodi",
    "dashboard.error.description": "Kulikuwa na hitilafu katika kupakia dashibodi.",
    "dashboard.error.hint": "Angalia konsoli kwa maelezo zaidi.",
    "dashboard.activity.title": "Shughuli za Hivi Karibuni",
    "dashboard.activity.live": "Moja kwa Moja",
    "dashboard.activity.none": "Hakuna shughuli za hivi karibuni",
    "dashboard.activity.view_all": "Tazama shughuli zote",
    "dashboard.quick_actions.title": "Vitendo vya Haraka",
    "dashboard.quick_actions.send_message": "Tuma Ujumbe",
    "dashboard.quick_actions.send_message_desc": "WhatsApp au SMS ya haraka",
    "dashboard.quick_actions.add_campaign": "Ongeza Kampeni Mpya",
    "dashboard.quick_actions.add_campaign_desc": "Kampeni ya ujumbe wa wingi",
    "dashboard.quick_actions.add_contacts": "Ongeza Anwani",
    "dashboard.quick_actions.add_contacts_desc": "Leta kutoka faili au ongeza mwenyewe",
    "dashboard.quick_actions.create_template": "Tengeneza Kiolezo",
    "dashboard.quick_actions.create_template_desc": "Kiolezo cha ujumbe",
    "dashboard.quick_actions.need_help": "Unahitaji msaada?",
    "dashboard.quick_actions.contact_support": "Wasiliana na Msaada →",
    "dashboard.quick_actions.view_tutorial": "Tazama Kuchimba",
    "dashboard.quick_actions.tutorial_description": "Tazama video ya kuchimba kuhusu jinsi ya kutumia Mifumo SMS",
    "dashboard.recent_campaigns.title": "Kampeni za Hivi Karibuni",
    "dashboard.recent_campaigns.view_all": "Tazama zote →",
    "dashboard.recent_campaigns.empty_title": "Bado hakuna kampeni",
    "dashboard.recent_campaigns.empty_subtitle": "Tengeneza kampeni yako ya kwanza ili kuanza",
    "dashboard.recent_campaigns.status.completed": "Imekamilika",
    "dashboard.recent_campaigns.status.sending": "Inatuma",
    "dashboard.recent_campaigns.status.scheduled": "Imeratibiwa",
    "dashboard.recent_campaigns.status.failed": "Imeshindwa",
    "dashboard.recent_campaigns.menu.view_details": "Tazama maelezo",
    "dashboard.recent_campaigns.menu.duplicate": "Nakili",
    "dashboard.recent_campaigns.menu.edit": "Hariri",
    "dashboard.recent_campaigns.progress": "Maendeleo",
    "dashboard.recent_campaigns.sent": "Imetumwa",
    "dashboard.recent_campaigns.delivered": "Imefika",
    "dashboard.recent_campaigns.opened": "Imefunguliwa",
    "dashboard.sender_ids.title": "Vitambulisho vya Mtumaji Hai",
    "dashboard.sender_ids.active": "Hai",
    "dashboard.sender_ids.table.sender_id": "Kitambulisho cha Mtumaji",
    "dashboard.sender_ids.table.status": "Hali",
    "dashboard.sender_ids.table.sample_content": "Maudhui ya Mfano",
    "dashboard.sender_ids.table.created": "Imetengenezwa",
    "dashboard.sender_ids.empty_title": "Hakuna vitambulisho vya mtumaji",
    "dashboard.sender_ids.empty_subtitle": "Vitambulisho vitaonekana hapa baada ya kuidhinishwa",
    "dashboard.sender_ids.manage": "Simamia vitambulisho vya mtumaji",
    "status.active": "Hai",
    "status.pending": "Inasubiri",
    "status.failed": "Imeshindwa",
    "status.sending": "Inatuma",
    "status.scheduled": "Imeratibiwa",
    "dashboard.performance.title": "Muhtasari wa Utendaji",
    "dashboard.performance.data.real": "Data Halisi",
    "dashboard.performance.data.loading": "Inapakia...",
    "dashboard.performance.chart.bar": "Nguzo",
    "dashboard.performance.chart.line": "Mstari",
    "dashboard.performance.chart.pie": "Mviringo",
    "dashboard.performance.chart.loading_title": "Inapakia data ya chati...",
    "dashboard.performance.chart.loading_subtitle": "Inachukua data ya wakati halisi kutoka hifadhidata",
    "dashboard.performance.chart.empty_title": "Hakuna chati bado",
    "dashboard.performance.chart.empty_subtitle": "Anza kutuma ujumbe kuona data ya utendaji",
    "dashboard.performance.chart.empty_pie_subtitle": "Jaribu kubadilisha hadi chati ya nguzo au mstari, au anza kutuma ujumbe",
    "dashboard.performance.chart.empty_trend_subtitle": "Anza kutuma ujumbe kuona mwenendo wa utendaji",
    "dashboard.performance.summary": "Jumla ya Ujumbe: {{total}} | Kiwango cha Uwasilishaji: {{rate}}%",
    "dashboard.performance.summary_loading": "Inapakia data ya utendaji...",
    "dashboard.performance.message_volume": "Kiasi cha Ujumbe",
    "dashboard.performance.delivery_rate": "Kiwango cha Uwasilishaji",
    "dashboard.empty.no_messages": "Hakuna ujumbe bado",
    "dashboard.empty.no_contacts": "Ongeza anwani kuanza",
    "dashboard.empty.no_campaigns": "Tengeneza kampeni",
    "dashboard.empty.no_sender_ids": "Omba kitambulisho cha mtumaji",
    "dashboard.empty.no_activity": "Hakuna shughuli bado",
    "dashboard.empty.no_data": "Hakuna data",
    "purchase_sms_credits": "Nunua Salio la SMS",
    "top_up_account": "Jaza akaunti yako ili kutuma ujumbe zaidi",
    "current_balance": "Salio Lako la Sasa",
    "choose_package": "Chagua Paketi",
    "enter_custom_amount": "Au Ingiza Kiasi Cha Kiadhari",
    "total_cost": "Jumla ya Gharama",
    "calculating": "Inahesabu...",
    "base_credits_from_package": "Salio la msingi kutoka paketi iliyochaguliwa. Bofya ili kuhariri na kukamatia.",
    "select_payment_method": "Chagua Njia ya Kulipa",
    "credits": "salio",
    "email_address": "Anwani ya Barua Pepe",
    "receipt_and_confirmation": "Tutakupigia risiti na uthibitisho wa malipo",
    "full_name": "Jina Kamili",
    "full_name_account": "Jina lako kamili kama linavyoonekana kwenye akaunti yako ya pesa za simu",
    "proceed_to_payment": "Endelea na Kulipa",
    "payment_in_progress": "Malipo Yanayoendelea",
    "confirm_purchase": "Thibitisha Ununuzi",
    "complete_payment_mobile": "Tafadhali kamili malipo kwenye simu yako",
    "review_order": "Kagua agizo lako kabla ya kuendelea",
    "total_amount": "Jumla ya Kiasi",
    "mobile_money_payment": "Malipo ya Pesa za Simu",
    "your_mobile_number": "Namba Yako ya Simu",
    "instructions": "Maelezo",
    "payment_instructions_text": "Baada ya kuthibitisha malipo, utapokea onyo wa pesa za simu kwenye simu yako. Kamili malipo ili kuongeza salio la SMS kwenye akaunti yako.",
    "cancel": "Ghairi",
    "processing": "Inaproceed...",
    "confirm_payment": "Thibitisha Malipo",
    "close": "Funga",
    "package": "Paketi",
    "sms_credits": "Salio la SMS",
    "payment_method": "Njia ya Kulipa",
    "enter_phone_number_mobile_money": "Ingiza namba ya simu iliyohusika na akaunti yako ya pesa za simu",
    "contacts": "Wasilianaji",
    "manage_customer_database": "Dhibiti hifadhidata yako ya wakilishi na mahusiano",
    "phone_number": "Namba ya Simu",
    "tags": "Lebo",
    "select_tags": "Chagua Lebo",
    "additional_info": "Taarifa Nyingine",
    "total": "jumla",
    "no_contacts_selected": "Hakuna wasilianaji waliochaguliwa",
    "please_select_contacts": "Tafadhali chagua wasilianaji",
    "enter_name": "Ingiza Jina",
    "add_contact": "Ongeza Wasilianaji",
    "export_contacts": "Eksport Wasilianaji",
    "import_contacts": "Ingiza Wasilianaji",
    "delete_contacts": "Futa Wasilianaji",
    "edit_contacts": "Hariri Wasilianaji",
    "add_tags": "Ongeza Lebo",
    "purchase_history": "Historia ya Ununuzi",
    "sender_names": "Majina ya Mtumaji",
    "integration_guide": "Mwongozo wa Ujumuishaji",
    "transaction_id": "Kitambulisho cha Muamala",
    "amount": "Kiasi",
    "status": "Hali",
    "date": "Tarehe",
    "sender_id": "Kitambulisho cha Mtumaji",
    "approved": "Imeidhinishwa",
    "pending": "Inasubiri",
    "rejected": "Ilikataliwa",
    "manage_sender_ids": "Simamia vitambulisho vyako vya mtumaji vilivoandikishwa kwa kampeni za SMS",
    "loading_sender_names": "Inapakia majina ya mtumaji...",
    "no_sender_names": "Hakuna majina ya mtumaji yanayopatikana",
    "unable_load_sender_names": "Haiwezi kupakia majina ya mtumaji. Tafadhali jaribu tena au wasiliana na msaada.",
    "error_loading_sender_names": "Kosa katika kupakia majina ya mtumaji",
    "loading_transactions": "Inapakia muamala...",
    "no_transactions": "Hakuna muamala iliyopatikana",
    "integration_documentation": "Nyaraka za API",
    "api_reference": "Rejea ya API",
    "quick_start": "Haraka Kuanza",
    "get_api_key": "Pata Ufunguo Wako wa API",
    "send_first_sms": "Tuma SMS Yako ya Kwanza",
    "check_balance": "Angalia Salio Lako",
    "view_all_credit_purchases": "Tazama ununuzi wako wote wa salio la SMS na muamala",
    "transaction_details": "Maelezo ya Muamala",
    "integration.quick_start_requests": "Ombi za Haraka Kuanza (cURL)",
    "integration.python_examples": "Mifano ya Python - Ujumuishaji wa Mshirika",
    "integration.endpoints": "Ncha za API",
    "integration.get_credit_balance_single": "Pata Salio la Salio (Mtenants Mmoja)",
    "integration.get_balance_for_specific": "Pata salio kwa mtenants mahsusi",
    "integration.get_credit_balance_all": "Pata Salio la Salio (Wateja Wote)",
    "integration.get_balance_for_all": "Pata salio kwa wateja wote",
    "integration.send_sms": "Tuma SMS Yako ya Kwanza",
    "integration.fire_production_request": "Utumie ombi la uzalishaji na payload ya JSON na ishara ya kubeba.",
    "integration.check_balance": "Angalia Salio Lako",
    "integration.confirm_remaining": "Thibitisha salio la SMS lililobaki kwa akaunti iliyoonekanika.",
    "integration.get_single_tenant": "Pata Salio la Salio (Mtenants Mmoja)",
    "integration.get_partner_integration": "Pata salio kwa mtenants mahsusi kwa kutumia ujumuishaji wa Mshirika.",
    "integration.get_all_clients": "Pata Salio la Salio (Wateja Wote)",
    "integration.get_all_clients_partner": "Pata salio kwa wateja wote kwa kutumia ujumuishaji wa Mshirika.",
    "integration.get_sms_usage_single": "Pata Utumiaji wa SMS na Mtumiaji (Mtenants Mmoja)",
    "integration.get_sms_usage_stats": "Pata takwimu za utumiaji wa SMS kwa mtenants mahsusi.",
    "integration.get_sms_usage_all": "Pata Utumiaji wa SMS na Mtumiaji (Mtenants Yote)",
    "integration.get_sms_usage_all_stats": "Pata takwimu za utumiaji wa SMS kwa mtenants yote.",
    "integration.authentication": "Uthibitisho",
    "integration.endpoints_label": "Ncha za API",
    "integration.quick_reference": "Rejea ya Haraka",
    "integration.base_url": "URL ya Msingi",
    "integration.support": "Msaada",
    "integration.email": "Barua Pepe",
    "integration.dashboard_link": "Dashibodi",
    "integration.version": "Toleo 1.3 · Ilibadilishwa Novemba 15, 2025 · Tayari kwa Uzalishaji.",
    "integration.step": "Hatua {{step}}",
  },
} as const;

type LanguageCode = keyof typeof translations;

type LanguageContextValue = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  t: (key: keyof typeof translations.en, params?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export { LanguageContext };

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    // Check both localStorage keys for backwards compatibility
    const storedPreference = typeof window !== "undefined" ? localStorage.getItem("language-preference") : null;
    const storedLegacy = typeof window !== "undefined" ? localStorage.getItem("language") : null;
    const stored = storedPreference || storedLegacy;

    if (stored === "sw" || stored === "en") {
      return stored;
    }
    return "en";
  });

  const setLanguage = (nextLanguage: LanguageCode) => {
    setLanguageState(nextLanguage);
    if (typeof window !== "undefined") {
      // Store in preferred key
      localStorage.setItem("language-preference", nextLanguage);
      // Also update legacy key for backwards compatibility
      localStorage.setItem("language", nextLanguage);
    }
  };

  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = useMemo(() => {
    return (key: keyof typeof translations.en, params?: Record<string, string | number>) => {
      const base = translations[language]?.[key] || translations.en[key] || String(key);
      if (!params) {
        return base;
      }
      return Object.keys(params).reduce((result, paramKey) => {
        return result.replace(new RegExp(`{{${paramKey}}}`, "g"), String(params[paramKey]));
      }, base);
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
