// API Configuration - Updated to match backend API documentation
export const API_CONFIG = {
	// BASE_URL: 'https://mifumosms.servehttp.com/api',
	BASE_URL: 'https://mifumosms.mifumolabs.com/api',
	ENDPOINTS: {
		AUTH: {
			LOGIN: '/auth/login/',
			REGISTER: '/auth/register/',
			PROFILE: '/auth/profile/',
			REFRESH: '/auth/token/refresh/',
			LOGOUT: '/auth/logout/',
			PASSWORD_CHANGE: '/auth/password/change/',
			PASSWORD_RESET: '/auth/password/reset/',
			PASSWORD_RESET_CONFIRM: '/auth/password/reset/confirm/',
			FORGOT_PASSWORD: '/auth/forgot-password/',
			VERIFY_PHONE: '/auth/verify-phone/',

			VERIFY_EMAIL: '/auth/verify-email/', // Also used for SMS verification codes
			ACTIVATE_ACCOUNT: (code: string) => `/auth/activate-account/${code}/`, // GET endpoint - code is 6-digit verification code
			RESEND_ACTIVATION: '/auth/resend-activation/', // POST endpoint - Handles SMS first, then email fallback
			API_KEY_GENERATE: '/auth/api-key/generate/',
			API_KEY_REVOKE: '/auth/api-key/revoke/',
			SMS: {
				VERIFY_CODE: '/auth/sms/verify-code/', // RECOMMENDED: POST endpoint for SMS verification
				SEND_CODE: '/auth/sms/send-code/', // Not used - backend handles via RESEND_ACTIVATION
				FORGOT_PASSWORD: '/auth/sms/forgot-password/',
				RESET_PASSWORD: '/auth/sms/reset-password/',
				CONFIRM_ACCOUNT: '/auth/sms/confirm-account/',
			},
			SETTINGS: {
				PROFILE: '/auth/settings/profile/',
				PREFERENCES: '/auth/settings/preferences/',
				NOTIFICATIONS: '/auth/settings/notifications/',
				SECURITY: '/auth/settings/security/',
				API: '/auth/settings/',
				API_KEYS: '/auth/settings/',
				KEYS: {
					CREATE: '/auth/keys/create/',
					REVOKE: (keyId: string) => `/auth/keys/${keyId}/revoke/`,
					REGENERATE: (keyId: string) => `/auth/keys/${keyId}/regenerate/`,
				},
				WEBHOOKS: {
					CREATE: '/auth/webhooks/create/',
					TOGGLE: (webhookId: string) => `/auth/webhooks/${webhookId}/toggle/`,
					DELETE: (webhookId: string) => `/auth/webhooks/${webhookId}/delete/`,
				},
			},
			SECURITY: {
				TWO_FACTOR_ENABLE: '/auth/security/2fa/enable/',
				TWO_FACTOR_DISABLE: '/auth/security/2fa/disable/',
			},
		},
		TENANTS: {
			BASE: '/tenants/',
			SWITCH: '/tenants/switch/',
			MEMBERS: (id: string) => `/tenants/${id}/members/`,
			DOMAINS: (id: string) => `/tenants/${id}/domains/`,
			TEAM: {
				LIST: (tenantId: string) => `/tenants/${tenantId}/team/`,
				STATS: (tenantId: string) => `/tenants/${tenantId}/team/stats/`,
				INVITE: (tenantId: string) => `/tenants/${tenantId}/team/invite/`,
				DETAIL: (tenantId: string, memberId: string) => `/tenants/${tenantId}/team/${memberId}/`,
				SUSPEND: (tenantId: string, memberId: string) => `/tenants/${tenantId}/team/${memberId}/suspend/`,
				ACTIVATE: (tenantId: string, memberId: string) => `/tenants/${tenantId}/team/${memberId}/activate/`,
				RESEND_INVITATION: (tenantId: string, memberId: string) => `/tenants/${tenantId}/team/${memberId}/resend-invitation/`,
				TRANSFER_OWNERSHIP: (tenantId: string, memberId: string) => `/tenants/${tenantId}/team/${memberId}/transfer-ownership/`,
			},
			INVITES: {
				ACCEPT: (token: string) => `/invite/${token}/accept/`,
				REJECT: (token: string) => `/invite/${token}/reject/`,
			},
		},
		MESSAGING: {
			CONTACTS: {
				BASE: '/messaging/contacts/',
				BULK_IMPORT: '/messaging/contacts/bulk-import/',
				BULK_DELETE: '/messaging/contacts/bulk-delete/',
				MOBILE_IMPORT: '/messaging/contacts/import/',
				DETAIL: (id: string) => `/messaging/contacts/${id}/`,
				OPT_IN: (id: string) => `/messaging/contacts/${id}/opt-in/`,
				OPT_OUT: (id: string) => `/messaging/contacts/${id}/opt-out/`,
			},
			SEGMENTS: '/messaging/segments/',
			TEMPLATES: '/messaging/templates/',
			TEMPLATE_SEND: (templateId: string) => `/messaging/templates/${templateId}/send/`,
			TEMPLATE_ACTIONS: {
				TOGGLE_FAVORITE: (id: string) => `/messaging/templates/${id}/toggle-favorite/`,
				INCREMENT_USAGE: (id: string) => `/messaging/templates/${id}/increment-usage/`,
				APPROVE: (id: string) => `/messaging/templates/${id}/approve/`,
				REJECT: (id: string) => `/messaging/templates/${id}/reject/`,
				VARIABLES: (id: string) => `/messaging/templates/${id}/variables/`,
				COPY: (id: string) => `/messaging/templates/${id}/copy/`,
			},
			TEMPLATE_STATISTICS: '/messaging/templates/statistics/',
			CONVERSATIONS: '/messaging/conversations/',
			MESSAGES: '/messaging/messages/',
			CAMPAIGNS: {
				BASE: '/messaging/campaigns/',
				SUMMARY: '/messaging/campaigns/summary/',
				DETAIL: (id: string) => `/messaging/campaigns/${id}/`,
				START: (id: string) => `/messaging/campaigns/${id}/start/`,
				PAUSE: (id: string) => `/messaging/campaigns/${id}/pause/`,
				CANCEL: (id: string) => `/messaging/campaigns/${id}/cancel/`,
				ANALYTICS: (id: string) => `/messaging/campaigns/${id}/analytics/`,
				DUPLICATE: (id: string) => `/messaging/campaigns/${id}/duplicate/`,
			},
			ANALYTICS: '/messaging/analytics/overview/',
			DASHBOARD: {
				OVERVIEW: '/messaging/dashboard/overview/',
				METRICS: '/messaging/dashboard/metrics/',
				COMPREHENSIVE: '/messaging/dashboard/comprehensive/',
			},
			ACTIVITY: {
				RECENT: '/messaging/activity/recent/',
			},
			PERFORMANCE: {
				OVERVIEW: '/messaging/performance/overview/',
			},
			SENDER_IDS: {
				BASE: '/messaging/sender-ids/',
				LIST: '/messaging/sender-ids/',
				REQUEST: '/messaging/sender-ids/request/',
				STATUS: (id: string) => `/messaging/sender-ids/${id}/status/`,
			},
			SENDER_NAMES: {
				UNIFIED: '/messaging/sms/sender-names/',
			},
			SMS: {
				SEND: '/messaging/sms/send/',
				QUICK: '/messaging/sms/quick/',
				STATUS: (messageId: string) => `/messaging/sms/${messageId}/status/`,
				HISTORY: '/messaging/sms/history/',
				STATS: '/messaging/sms/stats/',
				VALIDATE_PHONE: '/messaging/sms/validate-phone/',
				TEST_CONNECTION: '/messaging/sms/test-connection/',
				DELIVERY_REPORTS: '/sms/delivery-reports/',
				BALANCE: '/messaging/sms/balance/',
			},
			SENDER_ID_REQUESTS: {
				BASE: '/messaging/sender-requests/',
				REQUEST: '/messaging/sender-requests/',
				STATUS: (requestId: string) => `/messaging/sender-requests/${requestId}/`,
				DEFAULT: '/messaging/sender-id-requests/default/',
				DEFAULT_OVERVIEW: '/messaging/sender-id-requests/default/overview/',
				REQUEST_DEFAULT: '/messaging/sender-id-requests/request-default/',
				CANCEL_DEFAULT: '/messaging/sender-id-requests/cancel-default/',
				AVAILABLE: '/messaging/sender-id-requests/available/',
				USAGE: '/messaging/sender-id-usage/',
			},
		},
		BILLING: {
			BALANCE: '/billing/balance/',
			PURCHASE: '/billing/purchase/',
			PACKAGES: '/billing/packages/',
			HISTORY: '/billing/history/',
			PLANS: '/billing/plans/',
			SUBSCRIPTION: '/billing/subscription/',
			USAGE: '/billing/usage/',
			OVERVIEW: '/billing/overview/',
			PAYMENTS: {
				PROVIDERS: '/billing/payments/providers/',
				INITIATE: '/billing/payments/initiate/',
				VERIFY: (orderId: string) => `/billing/payments/verify/${orderId}/`,
				STATUS: (transactionId: string) => `/billing/payments/transactions/${transactionId}/status/`,
				PROGRESS: (transactionId: string) => `/billing/payments/transactions/${transactionId}/progress/`,
				ACTIVE: (transactionId: string) => `/billing/payments/transactions/${transactionId}/active/`,
				CANCEL: (transactionId: string) => `/billing/payments/transactions/${transactionId}/cancel/`,
				CLEANUP: (transactionId: string) => `/billing/payments/transactions/${transactionId}/cleanup/`,
				CUSTOM_CALCULATE: '/billing/payments/custom-sms/calculate/',
				CUSTOM_INITIATE: '/billing/payments/custom-sms/initiate/',
			},
			SMS: {
				BALANCE: '/billing/sms/balance/',
				PACKAGES: '/billing/sms/packages/',
				PURCHASE: '/billing/sms/purchase/',
				PURCHASES: '/billing/sms/purchases/',
				PURCHASE_HISTORY: '/billing/sms/purchases/history/',
				USAGE_STATISTICS: '/billing/sms/usage/statistics/',
			},
			HISTORY_DETAILED: {
				BASE: '/billing/history/',
				SUMMARY: '/billing/history/summary/',
				PURCHASES: '/billing/history/purchases/',
				PAYMENTS: '/billing/history/payments/',
				USAGE: '/billing/history/usage/',
				COMPREHENSIVE: '/billing/history/comprehensive/',
			},
		},
		INTEGRATION: {
			BASE: '/integration/v1',
			BRANDING: '/integration/branding/',
			USER_STATS: '/integration/user-stats/',
			QUICK_SEND: '/integration/quick-send/',
			CREDIT_PURCHASE: '/integration/credit-purchase/',
			LOW_CREDIT_USERS: '/integration/low-credit-users/',
			WEBHOOKS: '/integration/webhooks/',
			SYNC_CONTACTS: '/integration/sync-contacts/',
			CAMPAIGNS: '/integration/campaigns/',
			USER_PERMISSIONS: '/integration/user-permissions/',
			ANALYTICS: '/integration/analytics/',
			MIGRATE_DATA: '/integration/migrate-data/',
			SMS: {
				SEND: '/integration/v1/sms/send/',
				STATUS: (messageId: string) => `/integration/v1/sms/status/${messageId}/`,
				BALANCE: '/integration/v1/sms/balance/',
				DELIVERY_REPORTS: '/integration/v1/sms/delivery-reports/',
			},
			SENDER_ID: {
				REQUEST: '/integration/v1/sms/sender-id/request/',
				REQUESTS: '/integration/v1/sms/sender-id/requests/',
				AVAILABLE: '/integration/v1/sms/sender-id/available/',
			},
			PARTNER: {
				TENANT_CREATE: '/integration/v1/partner/tenants/create/',
				TENANT_DETAIL: (tenantId: string) => `/integration/v1/partner/tenants/${tenantId}/`,
				PACKAGES: '/integration/v1/partner/packages/',
				TENANT_CREDITS: (tenantId: string) => `/integration/v1/partner/tenants/${tenantId}/credits/`,
				TENANT_PAYMENT_INIT: (tenantId: string) => `/integration/v1/partner/tenants/${tenantId}/payments/initiate/`,
				TENANT_PAYMENT_STATUS: (tenantId: string, transactionId: string) =>
					`/integration/v1/partner/tenants/${tenantId}/payments/${transactionId}/status/`,
				CUSTOM_PAYMENT_INIT: (tenantId: string) => `/integration/v1/partner/tenants/${tenantId}/payments/custom/initiate/`,
				CUSTOM_PAYMENT_STATUS: (tenantId: string, purchaseId: string) =>
					`/integration/v1/partner/tenants/${tenantId}/payments/custom/${purchaseId}/status/`,
				PAYMENT_HISTORY: (tenantId: string) => `/integration/v1/partner/tenants/${tenantId}/payments/history/`,
				CALCULATE_PRICING: '/integration/v1/partner/pricing/calculate/',
			},
			PERTINA: {
				TENANT_BALANCE: (tenantId: string) => `/integration/v1/pertina/tenants/${tenantId}/balance/`,
				ALL_BALANCE: '/integration/v1/pertina/balance/',
				TENANT_USAGE: (tenantId: string) => `/integration/v1/pertina/tenants/${tenantId}/usage/`,
				ALL_USAGE: '/integration/v1/pertina/usage/',
			},
		},
		NOTIFICATIONS: {
			BASE: '/notifications/',
			LIST: '/notifications/',
			MARK_READ: (id: string) => `/notifications/${id}/mark-read/`,
			SETTINGS: '/notifications/settings/',
			RECENT: '/notifications/recent/',
			REAL: '/notifications/real/',
			UNREAD_COUNT: '/notifications/unread-count/',
			MARK_ALL_READ: '/notifications/mark-all-read/',
			STATS: '/notifications/stats/',
			SMS_CREDIT_TEST: '/notifications/sms-credit/test/',
			SYSTEM_CREATE: '/notifications/system/create/',
			SYSTEM_HEALTH_CHECK: '/notifications/system/health-check/',
			SYSTEM_REPORT_PROBLEM: '/notifications/system/report-problem/',
			SYSTEM_CLEANUP: '/notifications/system/cleanup/',
			TEMPLATES: '/notifications/templates/',
		},
	},
} as const;

// Helper function to build full URLs
export const buildApiUrl = (endpoint: string): string => {
	return `${API_CONFIG.BASE_URL}${endpoint}`;
};

// Helper function to get sender request endpoints
export const getSenderRequestEndpoints = () => API_CONFIG.ENDPOINTS.MESSAGING.SENDER_ID_REQUESTS;
