// API Configuration - Updated to match backend API documentation
export const API_CONFIG = {
	// BASE_URL: 'https://mifumosms.servehttp.com/api',
	BASE_URL: 'https://mifumosms.mifumolabs.com/api',
	ENDPOINTS: {
		AUTH: {
			LOGIN: '/auth/login/',
			REGISTER: '/auth/register/',
			PROFILE: '/auth/profile/',
			REFRESH: '/auth/token/refresh/',
			LOGOUT: '/auth/logout/',
			PASSWORD_CHANGE: '/auth/password/change/',
			PASSWORD_RESET: '/auth/password/reset/',
			PASSWORD_RESET_CONFIRM: '/auth/password/reset/confirm/',
			FORGOT_PASSWORD: '/auth/forgot-password/',
			VERIFY_PHONE: '/auth/verify-phone/',

			VERIFY_EMAIL: '/auth/verify-email/', // Also used for SMS verification codes
			ACTIVATE_ACCOUNT: (code: string) => `/auth/activate-account/${code}/`, // GET endpoint - code is 6-digit verification code
			RESEND_ACTIVATION: '/auth/resend-activation/', // POST endpoint - Handles SMS first, then email fallback
			API_KEY_GENERATE: '/auth/api-key/generate/',
			API_KEY_REVOKE: '/auth/api-key/revoke/',
			SMS: {
				VERIFY_CODE: '/auth/sms/verify-code/', // RECOMMENDED: POST endpoint for SMS verification
				SEND_CODE: '/auth/sms/send-code/', // Not used - backend handles via RESEND_ACTIVATION
				FORGOT_PASSWORD: '/auth/sms/forgot-password/',
				RESET_PASSWORD: '/auth/sms/reset-password/',
				CONFIRM_ACCOUNT: '/auth/sms/confirm-account/',
			},
			SETTINGS: {
				PROFILE: '/auth/settings/profile/',
				PREFERENCES: '/auth/settings/preferences/',
				NOTIFICATIONS: '/auth/settings/notifications/',
				SECURITY: '/auth/settings/security/',
				API: '/auth/settings/',
				API_KEYS: '/auth/settings/',
				KEYS: {
					CREATE: '/auth/keys/create/',
					REVOKE: (keyId: string) => `/auth/keys/${keyId}/revoke/`,
					REGENERATE: (keyId: string) => `/auth/keys/${keyId}/regenerate/`,
				},
				WEBHOOKS: {
					CREATE: '/auth/webhooks/create/',
					TOGGLE: (webhookId: string) => `/auth/webhooks/${webhookId}/toggle/`,
					DELETE: (webhookId: string) => `/auth/webhooks/${webhookId}/delete/`,
				},
			},
			SECURITY: {
				TWO_FACTOR_ENABLE: '/auth/security/2fa/enable/',
				TWO_FACTOR_DISABLE: '/auth/security/2fa/disable/',
			},
		},
		TENANTS: {
			BASE: '/tenants/',
			SWITCH: '/tenants/switch/',
			MEMBERS: (id: string) => `/tenants/${id}/members/`,
			DOMAINS: (id: string) => `/tenants/${id}/domains/`,
			TEAM: {
				LIST: (tenantId: string) => `/tenants/${tenantId}/team/`,
				STATS: (tenantId: string) => `/tenants/${tenantId}/team/stats/`,
				INVITE: (tenantId: string) => `/tenants/${tenantId}/team/invite/`,
				DETAIL: (tenantId: string, memberId: string) => `/tenants/${tenantId}/team/${memberId}/`,
				SUSPEND: (tenantId: string, memberId: string) => `/tenants/${tenantId}/team/${memberId}/suspend/`,
				ACTIVATE: (tenantId: string, memberId: string) => `/tenants/${tenantId}/team/${memberId}/activate/`,
				RESEND_INVITATION: (tenantId: string, memberId: string) => `/tenants/${tenantId}/team/${memberId}/resend-invitation/`,
				TRANSFER_OWNERSHIP: (tenantId: string, memberId: string) => `/tenants/${tenantId}/team/${memberId}/transfer-ownership/`,
			},
			INVITES: {
				ACCEPT: (token: string) => `/invite/${token}/accept/`,
				REJECT: (token: string) => `/invite/${token}/reject/`,
			},
		},
		MESSAGING: {
			CONTACTS: {
				BASE: '/messaging/contacts/',
				BULK_IMPORT: '/messaging/contacts/bulk-import/',
				BULK_DELETE: '/messaging/contacts/bulk-delete/',
				MOBILE_IMPORT: '/messaging/contacts/import/',
				DETAIL: (id: string) => `/messaging/contacts/${id}/`,
				OPT_IN: (id: string) => `/messaging/contacts/${id}/opt-in/`,
				OPT_OUT: (id: string) => `/messaging/contacts/${id}/opt-out/`,
			},
			SEGMENTS: '/messaging/segments/',
			TEMPLATES: '/messaging/templates/',
			TEMPLATE_SEND: (templateId: string) => `/messaging/templates/${templateId}/send/`,
			TEMPLATE_ACTIONS: {
				TOGGLE_FAVORITE: (id: string) => `/messaging/templates/${id}/toggle-favorite/`,
				INCREMENT_USAGE: (id: string) => `/messaging/templates/${id}/increment-usage/`,
				APPROVE: (id: string) => `/messaging/templates/${id}/approve/`,
				REJECT: (id: string) => `/messaging/templates/${id}/reject/`,
				VARIABLES: (id: string) => `/messaging/templates/${id}/variables/`,
				COPY: (id: string) => `/messaging/templates/${id}/copy/`,
			},
			TEMPLATE_STATISTICS: '/messaging/templates/statistics/',
			TEMPLATE_AVAILABLE_VARIABLES: '/messaging/templates/available-variables/',
			CONVERSATIONS: '/messaging/conversations/',
			MESSAGES: '/messaging/messages/',
			CAMPAIGNS: {
				BASE: '/messaging/campaigns/',
				SUMMARY: '/messaging/campaigns/summary/',
				DETAIL: (id: string) => `/messaging/campaigns/${id}/`,
				START: (id: string) => `/messaging/campaigns/${id}/start/`,
				PAUSE: (id: string) => `/messaging/campaigns/${id}/pause/`,
				CANCEL: (id: string) => `/messaging/campaigns/${id}/cancel/`,
				ANALYTICS: (id: string) => `/messaging/campaigns/${id}/analytics/`,
				DUPLICATE: (id: string) => `/messaging/campaigns/${id}/duplicate/`,
			},
			ANALYTICS: '/messaging/analytics/overview/',
			DASHBOARD: {
				OVERVIEW: '/messaging/dashboard/overview/',
				METRICS: '/messaging/dashboard/metrics/',
				COMPREHENSIVE: '/messaging/dashboard/comprehensive/',
			},
			ACTIVITY: {
				RECENT: '/messaging/activity/recent/',
			},
			PERFORMANCE: {
				OVERVIEW: '/messaging/performance/overview/',
			},
			SENDER_IDS: {
				BASE: '/messaging/sender-ids/',
				LIST: '/messaging/sender-ids/',
				REQUEST: '/messaging/sender-ids/request/',
				STATUS: (id: string) => `/messaging/sender-ids/${id}/status/`,
			},
			SENDER_NAMES: {
				UNIFIED: '/messaging/sender-ids/',
			},
			SMS: {
				SEND: '/messaging/sms/send/',
				QUICK: '/messaging/sms/quick/',
				STATUS: (messageId: string) => `/messaging/sms/${messageId}/status/`,
				HISTORY: '/messaging/sms/history/',
				STATS: '/messaging/sms/stats/',
				VALIDATE_PHONE: '/messaging/sms/validate-phone/',
				TEST_CONNECTION: '/messaging/sms/test-connection/',
				DELIVERY_REPORTS: '/sms/delivery-reports/',
				BALANCE: '/messaging/sms/balance/',
			},
			SENDER_ID_REQUESTS: {
				BASE: '/messaging/sender-requests/',
				REQUEST: '/messaging/sender-requests/',
				STATUS: (requestId: string) => `/messaging/sender-requests/${requestId}/`,
				DEFAULT: '/messaging/sender-id-requests/default/',
				DEFAULT_OVERVIEW: '/messaging/sender-id-requests/default/overview/',
				REQUEST_DEFAULT: '/messaging/sender-id-requests/request-default/',
				CANCEL_DEFAULT: '/messaging/sender-id-requests/cancel-default/',
				AVAILABLE: '/messaging/sender-id-requests/available/',
				USAGE: '/messaging/sender-id-usage/',
			},
			WHATSAPP_BILLING: {
				LOGS: '/messaging/whatsapp/billing/logs/',
				PRICING: '/messaging/whatsapp/billing/pricing/',
				BALANCE: '/messaging/whatsapp/billing/balance/',
			},
			WHATSAPP_CLOUD: {
				BASE: '/messaging/whatsapp/cloud/',
				SEND: (id: string) => `/messaging/whatsapp/cloud/${id}/send/`,
				SEND_AUTO: '/messaging/whatsapp/cloud/send/',
				SEND_BULK: (id: string) => `/messaging/whatsapp/cloud/${id}/send-bulk/`,
				SEND_BULK_AUTO: '/messaging/whatsapp/cloud/send-bulk/',
				GET_USERS: (id: string) => `/messaging/whatsapp/cloud/${id}/get-users/`,
				GET_USERS_AUTO: '/messaging/whatsapp/cloud/get-users/',
				AUDIENCE_CONTACTS: (id: string) => `/messaging/whatsapp/cloud/${id}/audience/contacts/`,
				AUDIENCE_CONTACTS_AUTO: '/messaging/whatsapp/cloud/audience/contacts/',
				AUDIENCE_PHONES: (id: string) => `/messaging/whatsapp/cloud/${id}/audience/phones/`,
				AUDIENCE_PHONES_AUTO: '/messaging/whatsapp/cloud/audience/phones/',
				MESSAGE_TEMPLATES: (id: string) => `/messaging/whatsapp/cloud/${id}/message-templates/`,
				MESSAGE_TEMPLATES_AUTO: '/messaging/whatsapp/cloud/message-templates/',
				MESSAGE_TEMPLATE_DETAIL: (id: string, templateId: string) =>
					`/messaging/whatsapp/cloud/${id}/message-templates/${templateId}/`,
				MESSAGE_TEMPLATE_DETAIL_AUTO: (templateId: string) =>
					`/messaging/whatsapp/cloud/message-templates/${templateId}/`,
				// §2.2 — builder endpoint: flat UI fields, server constructs components.
				MESSAGE_TEMPLATES_SIMPLE: (id: string) =>
					`/messaging/whatsapp/cloud/${id}/message-templates/simple/`,
				MESSAGE_TEMPLATES_SIMPLE_AUTO: '/messaging/whatsapp/cloud/message-templates/simple/',
				// §2.3 — dry-run preview for the builder (no submission).
				MESSAGE_TEMPLATES_SIMPLE_PREVIEW: (id: string) =>
					`/messaging/whatsapp/cloud/${id}/message-templates/simple/preview/`,
				MESSAGE_TEMPLATES_SIMPLE_PREVIEW_AUTO:
					'/messaging/whatsapp/cloud/message-templates/simple/preview/',
				SEND_FROM_TEMPLATE: (id: string) => `/messaging/whatsapp/cloud/${id}/send-from-template/`,
				SEND_FROM_TEMPLATE_AUTO: '/messaging/whatsapp/cloud/send-from-template/',
				// §1.4 — same view as send-from-template but the URL signals media/poll intent.
				SEND_TEMPLATE_RICH: (id: string) => `/messaging/whatsapp/cloud/${id}/send-template-rich/`,
				SEND_TEMPLATE_RICH_AUTO: '/messaging/whatsapp/cloud/send-template-rich/',
				SEND_BY_CATEGORY: (id: string) => `/messaging/whatsapp/cloud/${id}/send-by-category/`,
				SEND_BY_CATEGORY_AUTO: '/messaging/whatsapp/cloud/send-by-category/',
				SEND_BY_USER_IDS: (id: string) => `/messaging/whatsapp/cloud/${id}/send-by-user-ids/`,
				SEND_BY_USER_IDS_AUTO: '/messaging/whatsapp/cloud/send-by-user-ids/',
				SEND_BY_DATE_RANGE: (id: string) => `/messaging/whatsapp/cloud/${id}/send-by-date-range/`,
				SEND_BY_DATE_RANGE_AUTO: '/messaging/whatsapp/cloud/send-by-date-range/',
				CREDENTIALS: '/early-access/ai-copilots/whatsapp-credentials/',
				CREDENTIALS_SCOPED: (id: string) => `/early-access/ai-copilots/${id}/whatsapp-credentials/`,
				POLL_RESULTS: (pollId: string) => `/messaging/whatsapp/cloud/polls/${pollId}/results/`,
				POLL_BY_NAME: (name: string) => `/messaging/whatsapp/cloud/polls/by-name/${encodeURIComponent(name)}/`,
				POLL_BY_NAME_RESULTS: (name: string) => `/messaging/whatsapp/cloud/polls/by-name/${encodeURIComponent(name)}/results/`,
				POLL_LIST: '/messaging/whatsapp/cloud/polls/',
				POLL_CREATE: '/messaging/whatsapp/cloud/polls/',
				POLL_DETAIL: (pollId: string) => `/messaging/whatsapp/cloud/polls/${pollId}/`,
				BULK_IMAGE_SEND: '/whatsapp/bulk-image-send/',
				BULK_IMAGE_SEND_DETAIL: (jobId: string) => `/whatsapp/bulk-image-send/${jobId}/`,
			},
		},
		BILLING: {
			BALANCE: '/billing/balance/',
			PURCHASE: '/billing/purchase/',
			PACKAGES: '/billing/packages/',
			HISTORY: '/billing/history/',
			PLANS: '/billing/plans/',
			SUBSCRIPTION: '/billing/subscription/',
			USAGE: '/billing/usage/',
			OVERVIEW: '/billing/overview/',
			PAYMENTS: {
				PROVIDERS: '/billing/payments/providers/',
				INITIATE: '/billing/payments/initiate/',
				VERIFY: (orderId: string) => `/billing/payments/verify/${orderId}/`,
				STATUS: '/billing/payment-status/',
				PROGRESS: (transactionId: string) => `/billing/payments/transactions/${transactionId}/progress/`,
				ACTIVE: (transactionId: string) => `/billing/payments/transactions/${transactionId}/active/`,
				CANCEL: (transactionId: string) => `/billing/payments/transactions/${transactionId}/cancel/`,
				CLEANUP: (transactionId: string) => `/billing/payments/transactions/${transactionId}/cleanup/`,
				CUSTOM_CALCULATE: '/billing/payments/custom-sms/calculate/',
				CUSTOM_INITIATE: '/billing/payments/custom-sms/initiate/',
			},
			SMS: {
				BALANCE: '/billing/sms/balance/',
				PACKAGES: '/billing/sms/packages/',
				PURCHASE: '/billing/sms/purchase/',
				PURCHASE_HISTORY: '/billing/sms/purchases/history/',
				PURCHASE_STATS: '/billing/purchase-stats/',
				USAGE_STATISTICS: '/billing/sms/usage/statistics/',
				COST_CALCULATOR: '/billing/sms/cost-calculator/',
			},
			HISTORY_DETAILED: {
				BASE: '/billing/history/',
				SUMMARY: '/billing/history/summary/',
				PURCHASES: '/billing/history/purchases/',
				PAYMENTS: '/billing/history/payments/',
				USAGE: '/billing/history/usage/',
				COMPREHENSIVE: '/billing/history/comprehensive/',
			},
		},
		INTEGRATION: {
			BASE: '/integration/v1',
			BRANDING: '/integration/branding/',
			USER_STATS: '/integration/user-stats/',
			QUICK_SEND: '/integration/quick-send/',
			CREDIT_PURCHASE: '/integration/credit-purchase/',
			LOW_CREDIT_USERS: '/integration/low-credit-users/',
			WEBHOOKS: '/integration/webhooks/',
			SYNC_CONTACTS: '/integration/sync-contacts/',
			CAMPAIGNS: '/integration/campaigns/',
			USER_PERMISSIONS: '/integration/user-permissions/',
			ANALYTICS: '/integration/analytics/',
			MIGRATE_DATA: '/integration/migrate-data/',
			SMS: {
				SEND: '/integration/v1/sms/send/',
				STATUS: (messageId: string) => `/integration/v1/sms/status/${messageId}/`,
				BALANCE: '/integration/v1/sms/balance/',
				DELIVERY_REPORTS: '/integration/v1/sms/delivery-reports/',
			},
			SENDER_ID: {
				REQUEST: '/integration/v1/sms/sender-id/request/',
				REQUESTS: '/integration/v1/sms/sender-id/requests/',
				AVAILABLE: '/integration/v1/sms/sender-id/available/',
			},
			PARTNER: {
				TENANT_CREATE: '/integration/v1/partner/tenants/create/',
				TENANT_DETAIL: (tenantId: string) => `/integration/v1/partner/tenants/${tenantId}/`,
				PACKAGES: '/integration/v1/partner/packages/',
				TENANT_CREDITS: (tenantId: string) => `/integration/v1/partner/tenants/${tenantId}/credits/`,
				TENANT_PAYMENT_INIT: (tenantId: string) => `/integration/v1/partner/tenants/${tenantId}/payments/initiate/`,
				TENANT_PAYMENT_STATUS: (tenantId: string, transactionId: string) =>
					`/integration/v1/partner/tenants/${tenantId}/payments/${transactionId}/status/`,
				CUSTOM_PAYMENT_INIT: (tenantId: string) => `/integration/v1/partner/tenants/${tenantId}/payments/custom/initiate/`,
				CUSTOM_PAYMENT_STATUS: (tenantId: string, purchaseId: string) =>
					`/integration/v1/partner/tenants/${tenantId}/payments/custom/${purchaseId}/status/`,
				PAYMENT_HISTORY: (tenantId: string) => `/integration/v1/partner/tenants/${tenantId}/payments/history/`,
				CALCULATE_PRICING: '/integration/v1/partner/pricing/calculate/',
			},
			PERTINA: {
				TENANT_BALANCE: (tenantId: string) => `/integration/v1/pertina/tenants/${tenantId}/balance/`,
				ALL_BALANCE: '/integration/v1/pertina/balance/',
				TENANT_USAGE: (tenantId: string) => `/integration/v1/pertina/tenants/${tenantId}/usage/`,
				ALL_USAGE: '/integration/v1/pertina/usage/',
			},
		},
		NOTIFICATIONS: {
			BASE: '/notifications/',
			LIST: '/notifications/',
			MARK_READ: (id: string) => `/notifications/${id}/mark-read/`,
			SETTINGS: '/notifications/settings/',
			RECENT: '/notifications/recent/',
			REAL: '/notifications/real/',
			UNREAD_COUNT: '/notifications/unread-count/',
			MARK_ALL_READ: '/notifications/mark-all-read/',
			STATS: '/notifications/stats/',
			SMS_CREDIT_TEST: '/notifications/sms-credit/test/',
			SYSTEM_CREATE: '/notifications/system/create/',
			SYSTEM_HEALTH_CHECK: '/notifications/system/health-check/',
			SYSTEM_REPORT_PROBLEM: '/notifications/system/report-problem/',
			SYSTEM_CLEANUP: '/notifications/system/cleanup/',
			TEMPLATES: '/notifications/templates/',
			PUSH: {
				VAPID_PUBLIC_KEY: '/notifications/push/vapid-public-key/',
				SUBSCRIBE: '/notifications/push/subscribe/',
				UNSUBSCRIBE: '/notifications/push/unsubscribe/',
				TEST: '/notifications/push/test/',
				SEND: '/notifications/push/send/',
				BROADCAST: '/notifications/push/broadcast/',
			},
		},
		SENDA: {
			DASHBOARD: '/dashboard/',
			DASHBOARD_ENGAGEMENT: (days = 30) => `/dashboard/analytics/engagement/?days=${days}`,
			DASHBOARD_FUNNEL: '/dashboard/analytics/onboarding-funnel/',
			ONBOARDING: {
				STATUS: '/onboarding/status/',
				NEXT_STEP: '/onboarding/next-step/',
				COMPLETE_STEP: '/onboarding/complete-step/',
			},
			RECOMMENDATIONS: '/recommendations/',
			SCORES: '/user/scores/',
			BEHAVIOR: {
				TRACK: '/behavior/events/track/',
				EVENTS: '/behavior/events/',
				SCORES: '/behavior/scores/',
				SCORES_HISTORY: '/behavior/scores/history/',
				STAGES_HISTORY: '/behavior/stages/history/',
				ACTIVITY: '/behavior/activity/',
			},
		},
		EARLY_ACCESS: {
			AI_AGENTS: {
				STATUS: '/early-access/ai-copilots/status/',
				WAITLIST: '/early-access/ai-copilots/waitlist/',
				CREATE: '/early-access/ai-copilots/create/',
				LIST: '/early-access/ai-copilots/',
				DETAIL: (id: string) => `/early-access/ai-copilots/${id}/`,
				SAVE_FLOW: (id: string) => `/early-access/ai-copilots/${id}/flow/`,
				DEPLOY: (id: string) => `/early-access/ai-copilots/${id}/deploy/`,
				SIMULATE: (id: string) => `/early-access/ai-copilots/${id}/simulate/`,
				GENERATE: '/early-access/ai-copilots/generate/',
				GENERATE_AND_SAVE: '/early-access/ai-copilots/generate-and-save/',
				WHATSAPP_CREDENTIALS: (id: string) => `/early-access/ai-copilots/${id}/whatsapp-credentials/`,
				WHATSAPP_CREDENTIALS_AUTO: '/early-access/ai-copilots/whatsapp-credentials/',
				WEBHOOKS: {
					CREATE: (id: string) => `/early-access/ai-copilots/${id}/webhooks/`,
					TRIGGER: (id: string, action: string) => `/early-access/ai-copilots/${id}/webhooks/${action}/`,
				},
			},
			VOICE_AGENTS: {
				STATUS: '/early-access/voice-copilots/status/',
				WAITLIST: '/early-access/voice-copilots/waitlist/',
				FEATURES: '/early-access/voice-copilots/features/',
				CREATE: '/early-access/voice-copilots/create/',
				LIST: '/early-access/voice-copilots/',
				DETAIL: (id: string) => `/early-access/voice-copilots/${id}/`,
				DEPLOY: (id: string) => `/early-access/voice-copilots/${id}/deploy/`,
				CALL_LOGS: (id: string) => `/early-access/voice-copilots/${id}/call-logs/`,
			},
		},
	},
} as const;

// Helper function to build full URLs
export const buildApiUrl = (endpoint: string): string => {
	return `${API_CONFIG.BASE_URL}${endpoint}`;
};

// Helper function to get sender request endpoints
export const getSenderRequestEndpoints = () => API_CONFIG.ENDPOINTS.MESSAGING.SENDER_ID_REQUESTS;
